import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useCallback, useEffect, useState } from "react";
import { useAuth } from "@/lib/auth";
import { getAutomationPreferences, saveAutomationPreferences, type AutomationPreferences } from "@/lib/automation/parity.functions";

export const Route=createFileRoute("/automation-settings")({component:AutomationSettingsPage});
const DEFAULTS:AutomationPreferences={manualReview:true,aiGeneratedResume:true,aiGeneratedCoverLetter:true,autoRetrySafeFailures:true};
function AutomationSettingsPage(){const navigate=useNavigate();const{user,loading}=useAuth();const[prefs,setPrefs]=useState(DEFAULTS);const[busy,setBusy]=useState(false);const[message,setMessage]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);
useEffect(()=>{if(!loading&&!user)void navigate({to:"/auth",replace:true});},[loading,user,navigate]);const load=useCallback(async()=>{if(!user)return;try{setPrefs(await getAutomationPreferences());setError(null);}catch(e){setError(e instanceof Error?e.message:"Could not load automation settings.");}},[user]);useEffect(()=>{void load();},[load]);
async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage(null);setError(null);try{await saveAutomationPreferences({data:prefs});setMessage("Automation preferences saved.");}catch(err){setError(err instanceof Error?err.message:"Could not save automation settings.");}finally{setBusy(false);}}
if(loading||!user)return <main style={page}>Loading automation settings…</main>;return <main style={page}><nav style={nav}><a href="/dashboard">Dashboard</a><a href="/review">Review Queue</a><a href="/applications">Applications</a><a href="/settings">Settings</a></nav><h1>Automation Settings</h1><p style={muted}>Choose full automation or keep human approval in the loop. CAPTCHA and unresolved sensitive/required questions always stop for you rather than being guessed.</p><form onSubmit={save} style={panel}><Toggle label="Manual Review Mode" detail="Hold applications in the Review Queue so you can inspect generated documents and unresolved questions before submission." checked={prefs.manualReview} set={v=>setPrefs(p=>({...p,manualReview:v}))}/><Toggle label="AI-tailored resume" detail="Generate a role-specific resume from verified profile facts." checked={prefs.aiGeneratedResume} set={v=>setPrefs(p=>({...p,aiGeneratedResume:v}))}/><Toggle label="AI-tailored cover letter" detail="Generate a role-specific cover letter from verified profile facts." checked={prefs.aiGeneratedCoverLetter} set={v=>setPrefs(p=>({...p,aiGeneratedCoverLetter:v}))}/><Toggle label="Retry safe failures automatically" detail="Retry failures that are known not to have reached the employer. Verification-uncertain submissions are never retried automatically, preventing duplicate applications." checked={prefs.autoRetrySafeFailures} set={v=>setPrefs(p=>({...p,autoRetrySafeFailures:v}))}/><button disabled={busy} style={button}>{busy?"Saving…":"Save automation settings"}</button></form>{message?<p style={{color:"#047857"}}>{message}</p>:null}{error?<p role="alert" style={{color:"#b91c1c"}}>{error}</p>:null}</main>}
function Toggle({label,detail,checked,set}:{label:string;detail:string;checked:boolean;set:(v:boolean)=>void}){return <label style={toggle}><input type="checkbox" checked={checked} onChange={e=>set(e.target.checked)}/><span><strong>{label}</strong><small style={{display:"block",color:"#6b7280",marginTop:4,lineHeight:1.45}}>{detail}</small></span></label>}
const page:React.CSSProperties={maxWidth:900,margin:"0 auto",padding:"40px 24px",fontFamily:"system-ui"};const nav:React.CSSProperties={display:"flex",gap:14,flexWrap:"wrap",marginBottom:28};const muted:React.CSSProperties={color:"#4b5563",lineHeight:1.6};const panel:React.CSSProperties={display:"grid",gap:14,border:"1px solid #e5e7eb",borderRadius:12,padding:20,marginTop:28};const toggle:React.CSSProperties={display:"flex",gap:10,alignItems:"flex-start",border:"1px solid #e5e7eb",borderRadius:10,padding:14};const button:React.CSSProperties={border:0,borderRadius:8,padding:"11px 14px",background:"#111827",color:"white",fontWeight:700,cursor:"pointer",width:"fit-content"};
