import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useCallback, useEffect, useState } from "react";
import { useAuth } from "@/lib/auth";
import { getPortalCredentials, listApplicationMessages, listAutomationApplications, queueForReview, retryFailedSubmission, type ApplicationMessage, type AutomationApplication, type PortalCredentialView } from "@/lib/automation/parity.functions";

export const Route=createFileRoute("/automation-center")({component:AutomationCenter});
function AutomationCenter(){const navigate=useNavigate();const{user,loading}=useAuth();const[apps,setApps]=useState<AutomationApplication[]>([]);const[selected,setSelected]=useState<string>("");const[messages,setMessages]=useState<ApplicationMessage[]>([]);const[creds,setCreds]=useState<PortalCredentialView|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null);
useEffect(()=>{if(!loading&&!user)void navigate({to:"/auth",replace:true});},[loading,user,navigate]);const load=useCallback(async()=>{if(!user)return;try{const rows=await listAutomationApplications();setApps(rows);if(!selected&&rows[0])setSelected(rows[0].applicationId);setError(null);}catch(e){setError(e instanceof Error?e.message:"Could not load automation applications.");}},[user,selected]);useEffect(()=>{void load();},[load]);
const loadDetails=useCallback(async()=>{if(!selected)return;try{const[m,c]=await Promise.all([listApplicationMessages({data:{applicationId:selected}}),getPortalCredentials({data:{applicationId:selected}})]);setMessages(m);setCreds(c);}catch(e){setError(e instanceof Error?e.message:"Could not load application automation details.");}},[selected]);useEffect(()=>{void loadDetails();},[loadDetails]);
async function action(kind:"review"|"retry"){if(!selected)return;setBusy(true);setNotice(null);setError(null);try{if(kind==="review"){await queueForReview({data:{applicationId:selected}});setNotice("Application added to the manual Review Queue.");}else{const result=await retryFailedSubmission({data:{applicationId:selected}});setNotice(`Retry result: ${result.state}. ${result.message}`);}await load();await loadDetails();}catch(e){setError(e instanceof Error?e.message:"Automation action failed.");}finally{setBusy(false);}}
if(loading||!user)return <main style={page}>Loading automation center…</main>;const current=apps.find(a=>a.applicationId===selected);return <main style={page}><nav style={nav}><a href="/dashboard">Dashboard</a><a href="/review">Review Queue</a><a href="/automation-settings">Automation Settings</a><a href="/applications">Applications</a></nav><h1>Automation Center</h1><p style={muted}>Automatic form filling uses your verified profile, saved answers and private documents. Failed safe attempts can be retried here; uncertain submissions are blocked from automatic retry to prevent duplicates.</p><section style={panel}><label style={{display:"grid",gap:6}}><strong>Application</strong><select value={selected} onChange={e=>setSelected(e.target.value)} style={input}><option value="">Choose an application</option>{apps.map(a=><option key={a.applicationId} value={a.applicationId}>{a.jobTitle} — {a.company}</option>)}</select></label>{current?<div style={grid}><Stat label="Application status" value={current.status}/><Stat label="Last automation state" value={current.lastAttemptState??"No attempt"}/><Stat label="Last error" value={current.lastErrorCategory??"None"}/></div>:null}{current?.lastErrorMessage?<p style={{color:"#7f1d1d"}}>{current.lastErrorMessage}</p>:null}<div style={{display:"flex",gap:10,flexWrap:"wrap"}}><button disabled={!selected||busy} onClick={()=>void action("review")} style={button}>Send to Review Queue</button><button disabled={!selected||busy} onClick={()=>void action("retry")} style={secondary}>Retry failed application</button>{selected?<a href={`/applications/${selected}`} style={secondaryLink}>Open application</a>:null}</div></section><section style={panel}><h2 style={{margin:0}}>Per-application inbox</h2>{messages.length===0?<p style={muted}>No employer messages have been received for this application yet.</p>:messages.map(m=><article key={m.id} style={messageCard}><strong>{m.subject??"(No subject)"}</strong><div style={muted}>{m.sender??"Unknown sender"} · {new Date(m.receivedAt).toLocaleString()}</div><p style={{whiteSpace:"pre-wrap"}}>{m.bodyText}</p></article>)}</section><section style={panel}><h2 style={{margin:0}}>Employer portal credentials</h2>{creds?<div style={grid}><Stat label="Portal" value={creds.portalUrl??"Not recorded"}/><Stat label="Username" value={creds.username??"Not recorded"}/><Stat label="Password" value={creds.password??"Not recorded"}/></div>:<p style={muted}>No employer portal credentials have been stored for this application.</p>}</section>{notice?<p style={{color:"#047857"}}>{notice}</p>:null}{error?<p role="alert" style={{color:"#b91c1c"}}>{error}</p>:null}</main>}
function Stat({label,value}:{label:string;value:string}){return <div style={stat}><small style={muted}>{label}</small><strong style={{display:"block",marginTop:4,wordBreak:"break-word"}}>{value}</strong></div>}
const page:React.CSSProperties={maxWidth:980,margin:"0 auto",padding:"40px 24px",fontFamily:"system-ui"};const nav:React.CSSProperties={display:"flex",gap:14,flexWrap:"wrap",marginBottom:28};const muted:React.CSSProperties={color:"#6b7280"};const panel:React.CSSProperties={display:"grid",gap:14,border:"1px solid #e5e7eb",borderRadius:12,padding:20,margin:"24px 0"};const input:React.CSSProperties={border:"1px solid #d1d5db",borderRadius:8,padding:"11px 12px",fontSize:16,background:"white"};const grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10};const stat:React.CSSProperties={border:"1px solid #e5e7eb",borderRadius:9,padding:12};const button:React.CSSProperties={border:0,borderRadius:8,padding:"10px 13px",background:"#111827",color:"white",fontWeight:700,cursor:"pointer"};const secondary:React.CSSProperties={border:"1px solid #d1d5db",borderRadius:8,padding:"10px 13px",background:"white",cursor:"pointer"};const secondaryLink:React.CSSProperties={...secondary,textDecoration:"none",color:"#111827"};const messageCard:React.CSSProperties={border:"1px solid #e5e7eb",borderRadius:9,padding:14};
