import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useCallback, useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/lib/auth";

export const Route = createFileRoute("/employer")({ component: EmployerPage });

type Candidate = { user_id:string; full_name:string; headline:string|null; city:string|null; region:string|null; country:string|null; career_summary:string|null; experience_highlights:string|null; education:string|null; certifications:string|null; languages:string|null; skills:string[]|null; is_mason:boolean };

function EmployerPage(){
  const navigate=useNavigate(); const {user,loading}=useAuth(); const [company,setCompany]=useState(""); const [recruiter,setRecruiter]=useState(""); const [website,setWebsite]=useState(""); const [ready,setReady]=useState(false); const [masonsOnly,setMasonsOnly]=useState(false); const [candidates,setCandidates]=useState<Candidate[]>([]); const [message,setMessage]=useState(""); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  useEffect(()=>{if(!loading&&!user)void navigate({to:"/auth",replace:true});},[loading,user,navigate]);
  const loadEmployer=useCallback(async()=>{if(!user)return;const {data,error:e}=await supabase.from("employer_profiles").select("company_name,recruiter_name,website_url").eq("user_id",user.id).maybeSingle();if(e){setError(e.message);return;}if(data){setCompany(data.company_name);setRecruiter(data.recruiter_name??"");setWebsite(data.website_url??"");setReady(true);}},[user]);
  useEffect(()=>{void loadEmployer();},[loadEmployer]);
  const search=useCallback(async()=>{if(!ready)return;setError(null);const {data,error:e}=await supabase.rpc("search_discoverable_candidates",{masons_only:masonsOnly});if(e){setError(e.message);return;}setCandidates((data??[]) as Candidate[]);},[ready,masonsOnly]);
  useEffect(()=>{void search();},[search]);
  async function saveEmployer(e:React.FormEvent){e.preventDefault();if(!user||!company.trim())return;setBusy(true);setError(null);const {error:x}=await supabase.from("employer_profiles").upsert({user_id:user.id,company_name:company.trim(),recruiter_name:recruiter.trim()||null,website_url:website.trim()||null},{onConflict:"user_id"});if(x)setError(x.message);else{setReady(true);setMessage("Employer profile saved.");}setBusy(false);}
  async function contact(candidateId:string){if(!user)return;const text=window.prompt("Message to this candidate (private interest request):");if(!text?.trim())return;const {error:e}=await supabase.from("employer_interest_requests").insert({employer_user_id:user.id,candidate_user_id:candidateId,message:text.trim(),status:"pending"});if(e)setError(e.message);else setMessage("Interest request sent without exposing the candidate's private contact information.");}
  if(loading||!user)return <main style={page}>Loading employer workspace…</main>;
  return <main style={page}><h1>Employer Talent Search</h1><p style={muted}>Search only candidates who explicitly chose to be discoverable. Private contact details, documents, applications and street addresses are never shown here.</p><form onSubmit={saveEmployer} style={panel}><h2 style={{margin:0}}>Employer profile</h2><label>Company<input value={company} onChange={e=>setCompany(e.target.value)} required style={input}/></label><label>Recruiter / hiring contact<input value={recruiter} onChange={e=>setRecruiter(e.target.value)} style={input}/></label><label>Company website<input value={website} onChange={e=>setWebsite(e.target.value)} type="url" style={input}/></label><button disabled={busy} style={button}>{busy?"Saving…":"Save employer profile"}</button></form>{ready?<section style={panel}><label style={{display:"flex",gap:8,alignItems:"center"}}><input type="checkbox" checked={masonsOnly} onChange={e=>setMasonsOnly(e.target.checked)}/><strong>Masons only</strong></label><button onClick={()=>void search()} style={secondary}>Refresh candidates</button>{candidates.length===0?<p style={muted}>No opted-in candidates match this filter.</p>:<div style={grid}>{candidates.map(c=><article key={c.user_id} style={card}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><h3 style={{margin:0}}>{c.full_name}</h3>{c.is_mason?<span style={badge}>Mason</span>:null}</div><strong>{c.headline??"Candidate"}</strong><div style={muted}>{[c.city,c.region,c.country].filter(Boolean).join(", ")||"Location not listed"}</div>{c.career_summary?<p>{c.career_summary}</p>:null}{c.skills?.length?<p><strong>Skills:</strong> {c.skills.join(", ")}</p>:null}{c.experience_highlights?<p><strong>Experience:</strong> {c.experience_highlights}</p>:null}{c.education?<p><strong>Education:</strong> {c.education}</p>:null}{c.certifications?<p><strong>Certifications:</strong> {c.certifications}</p>:null}{c.languages?<p><strong>Languages:</strong> {c.languages}</p>:null}<button onClick={()=>void contact(c.user_id)} style={button}>Send private interest request</button></article>)}</div>}</section>:null}{message?<p style={{color:"#047857"}}>{message}</p>:null}{error?<p role="alert" style={errorStyle}>{error}</p>:null}</main>;
}
const page:React.CSSProperties={maxWidth:1050,margin:"0 auto",padding:"40px 24px",fontFamily:"system-ui"};const muted:React.CSSProperties={color:"#6b7280"};const panel:React.CSSProperties={display:"grid",gap:14,border:"1px solid #e5e7eb",borderRadius:12,padding:20,margin:"24px 0"};const input:React.CSSProperties={display:"block",width:"100%",boxSizing:"border-box",marginTop:6,border:"1px solid #d1d5db",borderRadius:8,padding:"10px 12px"};const button:React.CSSProperties={border:0,borderRadius:8,padding:"10px 13px",background:"#111827",color:"white",cursor:"pointer",width:"fit-content"};const secondary:React.CSSProperties={...button,background:"#e5e7eb",color:"#111827"};const grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:14};const card:React.CSSProperties={border:"1px solid #d1d5db",borderRadius:10,padding:16,background:"#f9fafb"};const badge:React.CSSProperties={background:"#111827",color:"white",borderRadius:999,padding:"4px 9px",fontSize:12,height:"fit-content"};const errorStyle:React.CSSProperties={color:"#b91c1c",border:"1px solid #fecaca",background:"#fef2f2",padding:12,borderRadius:8};
