import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useCallback, useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/lib/auth";
import { applyWith357, type AutoApplyResult } from "@/lib/automation/auto-apply.functions";

export const Route=createFileRoute("/quick-apply")({component:QuickApply});
type SavedJob={id:string;title:string;company:string;location:string|null;source_url:string|null;ats_name:string|null};
function QuickApply(){const navigate=useNavigate();const{user,loading}=useAuth();const[jobs,setJobs]=useState<SavedJob[]>([]);const[busy,setBusy]=useState<string|null>(null);const[result,setResult]=useState<AutoApplyResult|null>(null);const[error,setError]=useState<string|null>(null);
useEffect(()=>{if(!loading&&!user)void navigate({to:"/auth",replace:true});},[loading,user,navigate]);const load=useCallback(async()=>{if(!user)return;const{data,error}=await supabase.from("jobs").select("id,title,company,location,source_url,ats_name").eq("created_by",user.id).order("created_at",{ascending:false});if(error)setError(error.message);else setJobs(data??[]);},[user]);useEffect(()=>{void load();},[load]);
async function apply(jobId:string){setBusy(jobId);setError(null);setResult(null);try{setResult(await applyWith357({data:{jobId}}));}catch(e){setError(e instanceof Error?e.message:"Could not start automated application.");}finally{setBusy(null);}}
if(loading||!user)return <main style={page}>Loading saved jobs…</main>;return <main style={page}><nav style={nav}><a href="/dashboard">Dashboard</a><a href="/discover">Discover</a><a href="/automation-settings">Automation Settings</a><a href="/review">Review Queue</a></nav><h1>Apply with 357</h1><p style={muted}>One action prepares the application, generates the AI-tailored resume and cover letter you enabled, fills supported ATS forms from verified facts, and either sends it to your Review Queue or continues automatically according to your settings.</p><p style={notice}>No credits. Auto-plan subscribers use the monthly plan. CAPTCHA, authentication walls and missing sensitive answers stop for you instead of being bypassed or guessed.</p>{result?<section style={success}><strong>{result.mode==="review"?"Prepared for review":"Automation started"}</strong><p>{result.message}</p><a href={`/applications/${result.applicationId}`}>Open application</a>{result.mode==="review"?<span> · <a href="/review">Review Queue</a></span>:null}</section>:null}{error?<p role="alert" style={{color:"#b91c1c"}}>{error}</p>:null}<section style={{display:"grid",gap:12,marginTop:24}}>{jobs.length===0?<p style={muted}>Save jobs from Discover first.</p>:jobs.map(job=><article key={job.id} style={card}><div><strong>{job.title}</strong><div style={muted}>{job.company}{job.location?` · ${job.location}`:""}</div><small style={muted}>ATS: {job.ats_name??"detect on run"}</small></div><button type="button" disabled={!job.source_url||busy!==null} onClick={()=>void apply(job.id)} style={button}>{busy===job.id?"Preparing…":"Apply with 357"}</button></article>)}</section></main>}
const page:React.CSSProperties={maxWidth:980,margin:"0 auto",padding:"40px 24px",fontFamily:"system-ui"};const nav:React.CSSProperties={display:"flex",gap:14,flexWrap:"wrap",marginBottom:28};const muted:React.CSSProperties={color:"#6b7280",lineHeight:1.55};const notice:React.CSSProperties={background:"#f9fafb",border:"1px solid #e5e7eb",padding:14,borderRadius:10,color:"#374151"};const card:React.CSSProperties={display:"flex",justifyContent:"space-between",gap:14,alignItems:"center",flexWrap:"wrap",border:"1px solid #e5e7eb",borderRadius:12,padding:18};const button:React.CSSProperties={border:0,borderRadius:8,padding:"10px 14px",background:"#111827",color:"white",fontWeight:750,cursor:"pointer"};const success:React.CSSProperties={border:"1px solid #bbf7d0",background:"#f0fdf4",padding:16,borderRadius:10,marginTop:20};
