import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useCallback, useEffect, useState } from "react";
import { useAuth } from "@/lib/auth";
import { applyWith357 } from "@/lib/automation/auto-apply.functions";
import { listSkippedJobs, restoreSkippedJob, type SkippedJob } from "@/lib/jobs/skipped.functions";

export const Route=createFileRoute("/skipped-jobs")({component:SkippedJobs});
function SkippedJobs(){const navigate=useNavigate();const{user,loading}=useAuth();const[jobs,setJobs]=useState<SkippedJob[]>([]);const[busy,setBusy]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);useEffect(()=>{if(!loading&&!user)void navigate({to:"/auth",replace:true});},[loading,user,navigate]);const load=useCallback(async()=>{if(!user)return;try{setJobs(await listSkippedJobs());setError(null);}catch(e){setError(e instanceof Error?e.message:"Could not load skipped jobs.");}},[user]);useEffect(()=>{void load();},[load]);async function reapply(job:SkippedJob){setBusy(job.id);setError(null);setMessage(null);try{const restored=await restoreSkippedJob({data:{id:job.id}});const result=await applyWith357({data:{jobId:restored.jobId}});setMessage(`${job.title}: ${result.message}`);await load();}catch(e){setError(e instanceof Error?e.message:"Could not re-apply.");}finally{setBusy(null);}}if(loading||!user)return <main style={page}>Loading skipped jobs…</main>;return <main style={page}><nav style={nav}><a href="/job-feed">Job Feed</a><a href="/dashboard">Dashboard</a><a href="/applications">Applications</a></nav><h1>Skipped Jobs</h1><p style={muted}>Every job you skip stays here so you can change your mind later. Re-apply restores it and starts the same automated 357 workflow.</p>{message?<p style={success}>{message}</p>:null}{error?<p role="alert" style={danger}>{error}</p>:null}<section style={{display:"grid",gap:12,marginTop:24}}>{jobs.length===0?<p style={muted}>No skipped jobs yet.</p>:jobs.map(job=><article key={job.id} style={card}><div><strong>{job.title}</strong><div style={muted}>{job.company}{job.location?` · ${job.location}`:""}</div><small style={muted}>Skipped {new Date(job.skippedAt).toLocaleString()}</small></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button disabled={busy!==null} onClick={()=>void reapply(job)} style={button}>{busy===job.id?"Preparing…":"Re-apply with 357"}</button><a href={job.sourceUrl} target="_blank" rel="noreferrer" style={link}>Open listing</a></div></article>)}</section></main>}
const page:React.CSSProperties={maxWidth:980,margin:"0 auto",padding:"40px 24px",fontFamily:"system-ui"};const nav:React.CSSProperties={display:"flex",gap:14,marginBottom:26};const muted:React.CSSProperties={color:"#6b7280",lineHeight:1.5};const card:React.CSSProperties={border:"1px solid #e5e7eb",borderRadius:12,padding:18,display:"flex",justifyContent:"space-between",gap:14,alignItems:"center",flexWrap:"wrap"};const button:React.CSSProperties={border:0,borderRadius:8,padding:"10px 13px",background:"#111827",color:"white",fontWeight:750,cursor:"pointer"};const link:React.CSSProperties={border:"1px solid #d1d5db",borderRadius:8,padding:"9px 12px",background:"white",textDecoration:"none",color:"#111827"};const success:React.CSSProperties={color:"#047857",background:"#f0fdf4",padding:12,borderRadius:8};const danger:React.CSSProperties={color:"#b91c1c",background:"#fef2f2",padding:12,borderRadius:8};
