import { createServerFn } from "@tanstack/react-start";
import { createClient } from "@supabase/supabase-js";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import type { DiscoveredJob } from "./discovery.functions";

function admin(){const url=process.env["SUPABASE_URL"]?.trim();const key=process.env["SUPABASE_SERVICE_ROLE_KEY"]?.trim();if(!url||!key)throw new Error("Supabase server configuration is incomplete.");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});}
function validateJob(value:DiscoveredJob):DiscoveredJob{if(!value||typeof value!=="object"||!value.sourceUrl?.trim()||!value.title?.trim()||!value.company?.trim())throw new Error("A valid discovered job is required.");return value;}
function validateId(value:{id:string}){const id=value?.id?.trim();if(!id)throw new Error("Skipped job ID is required.");return{id};}

export type SkippedJob=DiscoveredJob&{id:string;skippedAt:string};
export const skipJob=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator(validateJob).handler(async({data,context})=>{const db=admin();const{error}=await db.from("skipped_jobs").upsert({user_id:context.userId,external_id:data.externalId,source:data.source,title:data.title,company:data.company,location:data.location,description:data.description,source_url:data.sourceUrl,posted_at:data.postedAt,salary_min:data.salaryMin,salary_max:data.salaryMax,currency:data.currency,remote:data.remote,tags:data.tags,skipped_at:new Date().toISOString()},{onConflict:"user_id,source_url"});if(error)throw new Error(error.message);return{ok:true};});
export const listSkippedJobs=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context}):Promise<SkippedJob[]>=>{const db=admin();const{data,error}=await db.from("skipped_jobs").select("*").eq("user_id",context.userId).order("skipped_at",{ascending:false});if(error)throw new Error(error.message);return(data??[]).map(r=>({id:r.id,externalId:r.external_id,source:r.source as DiscoveredJob["source"],title:r.title,company:r.company,location:r.location,description:r.description,sourceUrl:r.source_url,postedAt:r.posted_at,salaryMin:r.salary_min==null?null:Number(r.salary_min),salaryMax:r.salary_max==null?null:Number(r.salary_max),currency:r.currency,remote:r.remote,tags:r.tags??[],skippedAt:r.skipped_at}));});
export const restoreSkippedJob=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator(validateId).handler(async({data,context})=>{const db=admin();const{data:row,error}=await db.from("skipped_jobs").select("*").eq("id",data.id).eq("user_id",context.userId).maybeSingle();if(error)throw new Error(error.message);if(!row)throw new Error("Skipped job not found.");const {detectAts}=await import("@/lib/automation/ats-detect");const detection=detectAts(row.source_url);const saved=await db.from("jobs").upsert({created_by:context.userId,title:row.title,company:row.company,location:row.location,description:row.description,source_url:row.source_url,posted_at:row.posted_at?String(row.posted_at).slice(0,10):null,salary_min:row.salary_min==null?null:Math.max(0,Math.round(Number(row.salary_min))),salary_max:row.salary_max==null?null:Math.max(0,Math.round(Number(row.salary_max))),currency:row.currency,work_arrangement:row.remote===true?"remote":null,ats_name:detection.provider==="unknown"?null:detection.provider},{onConflict:"created_by,source_url"}).select("id").single();if(saved.error)throw new Error(saved.error.message);await db.from("skipped_jobs").delete().eq("id",data.id).eq("user_id",context.userId);return{jobId:saved.data.id as string};});
