'use client'

import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en')

  const translations = {
    en: {
      // Navigation
      'nav.home': 'Home',
      'nav.find_jobs': 'Find Jobs',
      'nav.traveling_man': 'Traveling Man',
      'nav.post_job': 'Post a Job',
      'nav.advertising': 'Advertising',
      'nav.signin': 'Sign In',
      'nav.register': 'Register',

      // Footer
      'footer.quick_links': 'Quick Links',
      'footer.legal': 'Legal',
      'footer.terms': 'Terms of Service',
      'footer.privacy': 'Privacy Policy',
      'footer.all_rights': 'All rights reserved.',
      'footer.tagline': 'Building Careers. Strengthening Brotherhood.',

      // Find Jobs Page
      'page.find_jobs.title': 'Find Jobs',
      'page.find_jobs.subtitle': 'Discover Opportunities in the Masonic Community',
      'page.find_jobs.description': 'Search for jobs from Masonic-friendly employers across the United States. Filter by location, job type, and your preferences.',
      'page.find_jobs.filter.keyword': 'Keyword',
      'page.find_jobs.filter.category': 'Category',
      'page.find_jobs.filter.state': 'State',
      'page.find_jobs.filter.remote': 'Remote Work',
      'page.find_jobs.filter.traveling_man': 'Traveling Man Jobs',
      'page.find_jobs.search_button': 'Search Jobs',
      'page.find_jobs.no_jobs': 'No jobs found. Try adjusting your filters.',

      // Traveling Man Page
      'page.traveling_man.title': 'Traveling Man Jobs',
      'page.traveling_man.subtitle': 'Opportunities for Relocation and Travel',
      'page.traveling_man.description': 'Explore job opportunities designed for Masons who travel or are willing to relocate. Perfect for those seeking new experiences across the country.',
      'page.traveling_man.job_card': 'Job Opportunity',
      'page.traveling_man.location': 'Location',
      'page.traveling_man.type': 'Job Type',
      'page.traveling_man.view_details': 'View Details',

      // Post Job Page
      'page.post_job.title': 'Post a Job',
      'page.post_job.subtitle': 'Reach Qualified Masonic Candidates',
      'page.post_job.description': 'Post your job opening and connect with skilled professionals in the Masonic community.',
      'page.post_job.form.title': 'Job Title',
      'page.post_job.form.description': 'Job Description',
      'page.post_job.form.requirements': 'Requirements',
      'page.post_job.form.location': 'Location',
      'page.post_job.form.remote': 'Remote Work Available',
      'page.post_job.form.traveling_man': 'Traveling Man Opportunity',
      'page.post_job.form.compensation': 'Compensation Range',
      'page.post_job.form.masonic_friendly': 'Masonic-Friendly Employer',
      'page.post_job.form.self_attested': 'I affirm that I am a Mason in Good Standing',
      'page.post_job.submit': 'Post Job',
      'page.post_job.pricing_note': 'Standard listing: Free | Featured listing: Premium feature',

      // Advertising Page
      'page.advertising.title': 'Advertising',
      'page.advertising.subtitle': 'Promote Your Business to Masonic Professionals',
      'page.advertising.description': 'Advertise your products, services, or business to our engaged community of Masons and Masonic-friendly employers.',
      'page.advertising.option1.title': 'Standard Listing',
      'page.advertising.option1.description': 'Basic ad placement',
      'page.advertising.option1.price': 'Contact for pricing',
      'page.advertising.option2.title': 'Featured Listing',
      'page.advertising.option2.description': 'Premium visibility placement',
      'page.advertising.option2.price': 'Premium pricing',
      'page.advertising.option3.title': 'Advertising Placement',
      'page.advertising.option3.description': 'Custom advertising options',
      'page.advertising.option3.price': 'Custom pricing',
      'page.advertising.learn_more': 'Learn More',

      // Sign In Page
      'page.signin.title': 'Sign In',
      'page.signin.subtitle': 'Access Your 357NETWORK Account',
      'page.signin.form.email': 'Email Address',
      'page.signin.form.password': 'Password',
      'page.signin.form.remember': 'Remember me',
      'page.signin.form.forgot_password': 'Forgot password?',
      'page.signin.submit': 'Sign In',
      'page.signin.no_account': 'Don\'t have an account?',
      'page.signin.create_account': 'Create one',

      // Register Page
      'page.register.title': 'Create Account',
      'page.register.subtitle': 'Join the 357NETWORK Community',
      'page.register.role_selection': 'I am a:',
      'page.register.role.job_seeker': 'Job Seeker',
      'page.register.role.employer': 'Employer',
      'page.register.role.advertiser': 'Advertiser',
      'page.register.form.email': 'Email Address',
      'page.register.form.password': 'Password',
      'page.register.form.confirm_password': 'Confirm Password',
      'page.register.form.name': 'Full Name',
      'page.register.form.company': 'Company Name',
      'page.register.form.terms': 'I agree to the Terms of Service',
      'page.register.submit': 'Create Account',
      'page.register.have_account': 'Already have an account?',
      'page.register.sign_in': 'Sign in',

      // Terms Page
      'page.terms.title': 'Terms of Service',
      'page.terms.lastUpdated': 'Last updated:',
      'page.terms.section1.title': '1. Agreement to Terms',
      'page.terms.section1.content': 'By accessing and using 357NETWORK, you accept and agree to be bound by the terms and provision of this agreement.',
      'page.terms.section2.title': '2. Use License',
      'page.terms.section2.content': 'Permission is granted to temporarily download one copy of the materials (information or software) on 357NETWORK for personal, non-commercial transitory viewing only.',
      'page.terms.section3.title': '3. Disclaimer',
      'page.terms.section3.content': 'The materials on 357NETWORK are provided on an \'as is\' basis. 357NETWORK makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.',
      'page.terms.section4.title': '4. Limitations',
      'page.terms.section4.content': 'In no event shall 357NETWORK or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on 357NETWORK.',

      // Privacy Page
      'page.privacy.title': 'Privacy Policy',
      'page.privacy.lastUpdated': 'Last updated:',
      'page.privacy.subtitle': 'How We Protect Your Data',
      'page.privacy.section1_title': '1. Information We Collect',
      'page.privacy.section1_content': 'We collect information you provide directly, such as when you create an account, post a job, or contact us. This may include your name, email address, phone number, location, and professional information.',
      'page.privacy.section2_title': '2. How We Use Your Information',
      'page.privacy.section2_content': 'We use the information we collect to provide, maintain, and improve our services, process transactions, and communicate with you about updates and changes to our service.',
      'page.privacy.section3_title': '3. Information Sharing',
      'page.privacy.section3_content': 'We do not sell or rent your personal information to third parties. We may share information as required by law or to protect the rights and safety of our users and the public.',
      'page.privacy.section4_title': '4. Data Security',
      'page.privacy.section4_content': 'We implement appropriate technical and organizational measures designed to protect personal information against unauthorized access, alteration, disclosure, or destruction.',
      'page.privacy.section5_title': '5. Your Rights',
      'page.privacy.section5_content': 'You have the right to access, update, or delete your personal information at any time by contacting us.',
      'page.privacy.section6_title': '6. Cookies and Tracking',
      'page.privacy.section6_content': 'We use cookies and similar tracking technologies to enhance your experience. You can control cookie settings through your browser preferences.',
      'page.privacy.section7_title': '7. Third-Party Links',
      'page.privacy.section7_content': 'Our website may contain links to third-party websites. We are not responsible for the privacy practices of those sites. We encourage you to review their privacy policies.',
      'page.privacy.section8_title': '8. Policy Changes',
      'page.privacy.section8_content': 'We may update this privacy policy periodically. We will notify you of significant changes by updating the last updated date and seeking your consent if required by law.',
      'page.privacy.contact_title': 'Contact Us',
      'page.privacy.contact_content': 'If you have questions about this privacy policy or our data practices, please contact us at:',

      // Home Page
      'page.home.welcome_title': 'Welcome to 357NETWORK',
      'page.home.welcome_description': 'A professional employment network for Freemasons, Masonic-friendly employers, and job seekers.',
      'page.home.tagline_secondary': 'Building Careers. Strengthening Brotherhood.',
      'page.home.button_find_jobs': 'Find Jobs',
      'page.home.button_post_job': 'Post a Job',
      'page.home.card_job_seekers_title': 'For Job Seekers',
      'page.home.card_job_seekers_description': 'Discover opportunities with Masonic-friendly employers and connect with the community.',
      'page.home.card_employers_title': 'For Employers',
      'page.home.card_employers_description': 'Post job listings and reach qualified candidates who share Masonic values.',
      'page.home.card_traveling_title': 'Traveling Man',
      'page.home.card_traveling_description': 'Special opportunities for Masons seeking temporary or remote work across the United States.',
      'page.home.placeholder_note': 'Phase 1 Placeholder - Coming Soon: Navigation, Job Search, User Dashboards, and More',

      // Find Jobs Page - Additional
      'page.find_jobs.search_title': 'Search & Filter',
      'page.find_jobs.available_jobs': 'Available Jobs',
      'page.find_jobs.loading': 'Loading jobs...',
      'page.find_jobs.error': 'Error loading jobs',
      'page.find_jobs.no_jobs_description': 'Check back soon for new opportunities, or adjust your search filters.',
      'page.find_jobs.all_categories': 'All Categories',
      'page.find_jobs.category_skilled_trades': 'Skilled Trades',
      'page.find_jobs.category_construction': 'Construction',
      'page.find_jobs.category_technology': 'Technology',
      'page.find_jobs.category_sales': 'Sales',
      'page.find_jobs.category_healthcare': 'Healthcare',
      'page.find_jobs.all_states': 'All States',
      'page.find_jobs.job_title_placeholder': 'Job Title Placeholder',
      'page.find_jobs.company_name': 'Company Name',
      'page.find_jobs.city_state': 'City, State',
      'page.find_jobs.job_description_placeholder': 'Job description placeholder...',

      // Traveling Man Page - Additional
      'page.traveling_man.section_about_title': 'About Traveling Man Jobs',
      'page.traveling_man.section_about_description': 'Traveling Man opportunities are ideal for Masons seeking temporary work, relocation, or travel-based employment. These positions offer flexibility and the chance to work with Masonic-friendly employers across the United States.',
      'page.traveling_man.opportunities_title': 'Traveling Man Opportunities',
      'page.traveling_man.badge_text': 'Traveling Man',
      'page.traveling_man.project_title': 'Temporary Project Work',
      'page.traveling_man.duration_3_6': 'Temporary (3-6 months)',
      'page.traveling_man.relocation_support': 'Temporary work opportunity with relocation support...',
      'page.traveling_man.consulting_title': 'Remote Consulting',
      'page.traveling_man.duration_flexible': 'Flexible Remote',
      'page.traveling_man.consulting_description': 'Travel-friendly consulting position with flexible scheduling...',
      'page.traveling_man.seasonal_title': 'Seasonal Contract',
      'page.traveling_man.duration_seasonal': 'Contract',
      'page.traveling_man.seasonal_description': 'Seasonal work with travel accommodations provided...',
      'page.traveling_man.multiple_states': 'Multiple States',
      'page.traveling_man.seasonal_rotation': 'Seasonal Rotation',

      // Post Job Page - Additional
      'page.post_job.form_title': 'Job Posting Form',
      'page.post_job.job_title': 'Job Title',
      'page.post_job.company_name': 'Company Name',
      'page.post_job.category': 'Category',
      'page.post_job.location': 'Location',
      'page.post_job.job_description': 'Job Description',
      'page.post_job.salary': 'Compensation Range',
      'page.post_job.requirements': 'Requirements',
      'page.post_job.contact_email': 'Contact Email',
      'page.post_job.remote_position': 'Remote Work Available',
      'page.post_job.traveling_man_eligible': 'Traveling Man Opportunity',
      'page.post_job.select_category': 'Select a category...',
      'page.post_job.salary_placeholder': '$50,000 - $75,000',
      'page.post_job.requirements_placeholder': 'Required skills and qualifications (optional)',
      'page.post_job.email_placeholder': 'contact@example.com',
      'page.post_job.city_placeholder': 'City',
      'page.post_job.state_placeholder': 'CA',
      'page.post_job.submit_button': 'Post Job',
      'page.post_job.posting_button': 'Posting...',
      'page.post_job.attestation_required': 'Mason in Good Standing self-attestation is required to post',
      'page.post_job.payment_section_title': 'Payment Options',
      'page.post_job.payment_card_standard': 'Standard Job Listing',
      'page.post_job.payment_card_featured': 'Featured Job Listing',
      'page.post_job.payment_price_standard': '$29',
      'page.post_job.payment_price_featured': '$79',
      'page.post_job.payment_duration': 'for 30 days',
      'page.post_job.payment_button': 'Proceed to Payment',
      'page.post_job.payment_processing': 'Processing...',
      'page.post_job.stripe_not_configured': 'Stripe payment is not configured yet',
      'page.post_job.section_pricing': 'Posting Pricing',
      'page.post_job.pricing_standard': 'Standard Listing',
      'page.post_job.pricing_featured': 'Featured Listing',
      'page.post_job.pricing_standard_desc': 'Post your job for 30 days with standard visibility on 357NETWORK.',
      'page.post_job.pricing_featured_desc': 'Premium visibility with featured placement on job search results.',
      'page.post_job.error_login_required': 'You must be logged in to post a job',
      'page.post_job.error_payment_missing': 'User information or job ID is missing',

      // Advertising Page - Additional
      'page.advertising.choose_option': 'Choose Your Advertising Option',
      'page.advertising.standard.title': 'Standard Listing',
      'page.advertising.standard.duration': '30 days - $199',
      'page.advertising.standard.feature1': 'Basic ad placement',
      'page.advertising.standard.feature2': 'Homepage visibility',
      'page.advertising.standard.feature3': 'Community access',
      'page.advertising.standard.feature4': 'Email notifications',
      'page.advertising.featured.title': 'Featured Listing',
      'page.advertising.featured.duration': '30 days - $399',
      'page.advertising.featured.feature1': 'Premium visibility',
      'page.advertising.featured.feature2': 'Featured placement',
      'page.advertising.featured.feature3': 'Top page position',
      'page.advertising.featured.feature4': 'Priority email notifications',
      'page.advertising.featured.feature5': 'Analytics dashboard',
      'page.advertising.placement.title': 'Advertising Placement',
      'page.advertising.placement.duration': '30 days - $199',
      'page.advertising.placement.feature1': 'Custom ad placement',
      'page.advertising.placement.feature2': 'Flexible positioning',
      'page.advertising.placement.feature3': 'Community reach',
      'page.advertising.placement.feature4': 'Standard support',
      'page.advertising.choose_button': 'Choose This Option',
      'page.advertising.how_it_works': 'How It Works',
      'page.advertising.step1.title': 'Select Your Option',
      'page.advertising.step1.description': 'Choose the advertising option that best fits your needs and budget.',
      'page.advertising.step2.title': 'Provide Your Content',
      'page.advertising.step2.description': 'Submit your ad content, images, and targeting preferences.',
      'page.advertising.step3.title': 'Checkout',
      'page.advertising.step3.description': 'Complete the payment process securely through our platform.',
      'page.advertising.step4.title': 'Go Live',
      'page.advertising.step4.description': 'Your ad goes live and reaches the 357NETWORK community.',
      'page.advertising.error_login_required': 'You must be logged in to purchase advertising',

      // Sign In Page - Additional
      'page.signin.form_title': 'Enter Your Credentials',
      'page.signin.email': 'Email Address',
      'page.signin.email_placeholder': 'your@email.com',
      'page.signin.password': 'Password',
      'page.signin.password_placeholder': 'Enter your password',
      'page.signin.remember_me': 'Remember me',
      'page.signin.submit_button': 'Sign In',
      'page.signin.forgot_password': 'Forgot your password?',
      'page.signin.reset_link': 'Reset it here',
      'page.signin.signup_link': 'Sign up here',
      'page.signin.benefits_title': 'Benefits of 357NETWORK',
      'page.signin.benefit1_title': 'Network with Masons',
      'page.signin.benefit1_description': 'Connect with fellow Freemasons in your profession and community.',
      'page.signin.benefit2_title': 'Find Quality Jobs',
      'page.signin.benefit2_description': 'Access job opportunities from Masonic-friendly employers.',
      'page.signin.benefit3_title': 'Grow Your Career',
      'page.signin.benefit3_description': 'Advance your professional goals within the Masonic brotherhood.',
      'page.signin.error_required_fields': 'Email and password are required',
      'page.signin.error_login_failed': 'Login failed. Please try again.',

      // Register Page - Additional
      'page.register.form_title': 'Account Information',
      'page.register.account_type': 'I am a:',
      'page.register.job_seeker': 'Job Seeker',
      'page.register.job_seeker_description': 'Looking for employment opportunities',
      'page.register.employer': 'Employer',
      'page.register.employer_description': 'Hiring qualified candidates',
      'page.register.advertiser': 'Advertiser',
      'page.register.advertiser_description': 'Promoting products and services',
      'page.register.first_name': 'First Name',
      'page.register.last_name': 'Last Name',
      'page.register.email': 'Email Address',
      'page.register.email_placeholder': 'your@email.com',
      'page.register.password': 'Password',
      'page.register.password_placeholder': 'At least 8 characters',
      'page.register.confirm_password': 'Confirm Password',
      'page.register.confirm_password_placeholder': 'Re-enter your password',
      'page.register.agree_terms': 'I agree to the',
      'page.register.terms_link': 'Terms of Service',
      'page.register.submit_button': 'Create Account',
      'page.register.submitting': 'Creating Account',
      'page.register.signin_link': 'Sign in instead',
      'page.register.error_all_fields_required': 'All fields are required',
      'page.register.error_invalid_email': 'Please enter a valid email address',
      'page.register.error_password_length': 'Password must be at least 8 characters',
      'page.register.error_password_mismatch': 'Passwords do not match',
      'page.register.error_role_required': 'Please select an account type',
      'page.register.error_terms_required': 'You must agree to the terms and conditions',
      'page.register.error_signup_failed': 'Sign up failed. Please try again.',
      'page.register.pending_intake_success': 'Your registration request has been received!',

      // Terms Page - Additional
      'page.terms.subtitle': 'Understanding Our Service Agreement',
      'page.terms.section1_title': '1. Agreement to Terms',
      'page.terms.section1_content': 'By accessing and using 357NETWORK, you accept and agree to be bound by the terms and provision of this agreement.',
      'page.terms.section2_title': '2. Use License',
      'page.terms.section2_content': 'Permission is granted to temporarily download one copy of the materials (information or software) on 357NETWORK for personal, non-commercial transitory viewing only.',
      'page.terms.section3_title': '3. Disclaimer',
      'page.terms.section3_content': 'The materials on 357NETWORK are provided on an \'as is\' basis. 357NETWORK makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.',
      'page.terms.section4_title': '4. Limitations',
      'page.terms.section4_content': 'In no event shall 357NETWORK or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on 357NETWORK.',
      'page.terms.section5_title': '5. Accuracy of Materials',
      'page.terms.section5_content': 'The materials appearing on 357NETWORK could include technical, typographical, or photographic errors. 357NETWORK does not warrant that any of the materials on its website are accurate, complete, or current.',
      'page.terms.section6_title': '6. Links',
      'page.terms.section6_content': '357NETWORK has not reviewed all of the sites linked to its website and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by 357NETWORK of the site. Use of any such linked website is at the user\'s own risk.',
      'page.terms.section7_title': '7. Modifications',
      'page.terms.section7_content': '357NETWORK may revise these terms of service for its website at any time without notice. By using this website, you are agreeing to be bound by the then current version of these terms of service.',
      'page.terms.section8_title': '8. Governing Law',
      'page.terms.section8_content': 'These terms and conditions are governed by and construed in accordance with the laws of the United States, and you irrevocably submit to the exclusive jurisdiction of the courts in that location.',
      'page.terms.contact_title': 'Contact Information',
      'page.terms.contact_content': 'If you have questions about these terms of service, please contact us at:',

      // Dashboard Pages
      'dashboard.job_seeker.title': 'Job Seeker Dashboard',
      'dashboard.job_seeker.subtitle': 'Welcome to your career hub',
      'dashboard.job_seeker.profile_summary': 'Profile Summary',
      'dashboard.job_seeker.welcome_message': 'Welcome, Job Seeker!',
      'dashboard.job_seeker.profile_help': 'Your profile helps employers find you. Complete your profile to increase your visibility and match with more job opportunities.',
      'dashboard.job_seeker.full_name': 'Full Name',
      'dashboard.job_seeker.full_name_placeholder': 'Your name',
      'dashboard.job_seeker.professional_title': 'Professional Title',
      'dashboard.job_seeker.professional_title_placeholder': 'Your professional title',
      'dashboard.job_seeker.location': 'Location',
      'dashboard.job_seeker.location_placeholder': 'City, State',
      'dashboard.job_seeker.bio': 'Bio',
      'dashboard.job_seeker.bio_placeholder': 'Tell employers about yourself',
      'dashboard.job_seeker.button_update_profile': 'Update Profile',
      'dashboard.job_seeker.saved_jobs': 'Saved Jobs',
      'dashboard.job_seeker.no_saved_jobs': 'No Saved Jobs Yet',
      'dashboard.job_seeker.saved_jobs_help': 'Start saving jobs from the job listings to view them here. Saved jobs help you keep track of opportunities you\'re interested in.',
      'dashboard.job_seeker.button_browse_jobs': 'Browse Jobs',
      'dashboard.job_seeker.applications_history': 'Applications History',
      'dashboard.job_seeker.no_applications': 'No Applications Yet',
      'dashboard.job_seeker.applications_help': 'Applications you submit to job listings will appear here. Track your application status and next steps.',
      'dashboard.job_seeker.button_view_jobs': 'View Jobs',
      'dashboard.job_seeker.recommended_jobs': 'Recommended Jobs',
      'dashboard.job_seeker.no_recommendations': 'No Recommendations Yet',
      'dashboard.job_seeker.recommendations_help': 'Complete your profile to receive personalized job recommendations that match your skills and preferences.',
      'dashboard.job_seeker.button_complete_profile': 'Complete Profile',

      'dashboard.employer.title': 'Employer Dashboard',
      'dashboard.employer.subtitle': 'Manage your job postings and applications',
      'dashboard.employer.company_profile': 'Company Profile Summary',
      'dashboard.employer.company_info': 'Company Information',
      'dashboard.employer.company_info_help': 'Maintain your company profile to attract qualified candidates and provide them with information about your organization.',
      'dashboard.employer.company_name': 'Company Name',
      'dashboard.employer.company_name_placeholder': 'Your company name',
      'dashboard.employer.company_website': 'Company Website',
      'dashboard.employer.company_website_placeholder': 'https://yourcompany.com',
      'dashboard.employer.location': 'Location',
      'dashboard.employer.location_placeholder': 'City, State',
      'dashboard.employer.company_description': 'Company Description',
      'dashboard.employer.company_description_placeholder': 'Tell job seekers about your company',
      'dashboard.employer.masonic_status': 'Masonic-Friendly Status',
      'dashboard.employer.masonic_select': 'Select status',
      'dashboard.employer.masonic_yes': 'Yes, we are masonic-friendly',
      'dashboard.employer.masonic_no': 'No, not applicable',
      'dashboard.employer.button_update_company': 'Update Company Profile',
      'dashboard.employer.posted_jobs': 'Posted Jobs',
      'dashboard.employer.button_post_new_job': 'Post a New Job',
      'dashboard.employer.no_posted_jobs': 'No Posted Jobs Yet',
      'dashboard.employer.posted_jobs_help': 'You haven\'t posted any jobs yet. Start by posting your first job opening to connect with qualified candidates.',
      'dashboard.employer.button_create_job': 'Create Job Posting',
      'dashboard.employer.job_applications': 'Job Applications',
      'dashboard.employer.no_applications': 'No Applications Yet',
      'dashboard.employer.applications_help': 'Applications from job seekers will appear here. You\'ll be able to review, message, and manage candidates.',
      'dashboard.employer.button_view_applications': 'View All Applications',
      'dashboard.employer.billing_subscriptions': 'Billing & Subscriptions',
      'dashboard.employer.subscription_status': 'Subscription Status',
      'dashboard.employer.billing_help1': 'Billing information and subscription details will appear here.',
      'dashboard.employer.billing_help2': 'Manage your account tier, upgrade features, and view invoice history.',
      'dashboard.employer.button_manage_subscription': 'Manage Subscription',
      'dashboard.employer.button_view_invoices': 'View Invoices',

      'dashboard.advertiser.title': 'Advertiser Dashboard',
      'dashboard.advertiser.subtitle': 'Manage your advertisements and campaigns',
      'dashboard.advertiser.active_ads': 'Active Advertisements',
      'dashboard.advertiser.button_create_ad': 'Create New Advertisement',
      'dashboard.advertiser.no_active_ads': 'No Active Advertisements',
      'dashboard.advertiser.ads_help': 'You haven\'t created any advertisements yet. Start by creating your first ad to reach the 357NETWORK community.',
      'dashboard.advertiser.campaign_performance': 'Campaign Performance',
      'dashboard.advertiser.performance_metrics': 'Performance Metrics',
      'dashboard.advertiser.metrics_help': 'Campaign performance data will be displayed here.',
      'dashboard.advertiser.total_impressions': 'Total Impressions',
      'dashboard.advertiser.total_clicks': 'Total Clicks',
      'dashboard.advertiser.click_through_rate': 'Click-Through Rate',
      'dashboard.advertiser.conversion_rate': 'Conversion Rate',
      'dashboard.advertiser.button_detailed_analytics': 'View Detailed Analytics',
      'dashboard.advertiser.billing_subscriptions': 'Billing & Subscriptions',
      'dashboard.advertiser.advertising_account': 'Advertising Account',
      'dashboard.advertiser.billing_help1': 'Manage your advertising budget, payment method, and billing history.',
      'dashboard.advertiser.billing_help2': 'Upgrade your subscription to unlock premium advertising features.',
      'dashboard.advertiser.button_manage_billing': 'Manage Billing',
      'dashboard.advertiser.button_view_invoices': 'View Invoices',
      'dashboard.advertiser.ad_settings': 'Advertisement Settings',
      'dashboard.advertiser.ad_preferences': 'Advertising Preferences',
      'dashboard.advertiser.business_name': 'Business Name',
      'dashboard.advertiser.business_name_placeholder': 'Your business name',
      'dashboard.advertiser.business_website': 'Business Website',
      'dashboard.advertiser.business_website_placeholder': 'https://yourbusiness.com',
      'dashboard.advertiser.ad_category': 'Primary Ad Category',
      'dashboard.advertiser.category_select': 'Select category',
      'dashboard.advertiser.category_products': 'Products & Services',
      'dashboard.advertiser.category_professional': 'Professional Services',
      'dashboard.advertiser.category_events': 'Events & Sponsorship',
      'dashboard.advertiser.category_other': 'Other',
      'dashboard.advertiser.business_description': 'Business Description',
      'dashboard.advertiser.business_description_placeholder': 'Describe your business and what you\'re advertising',
      'dashboard.advertiser.masonic_friendly': 'Masonic-Friendly Business',
      'dashboard.advertiser.button_save_settings': 'Save Settings',

      'dashboard.admin.title': 'Admin Dashboard - Approvals',
      'dashboard.admin.subtitle': 'System administration and content moderation',
      'dashboard.admin.statistics': 'System Statistics',
      'dashboard.admin.stat_total_users': 'Total Users',
      'dashboard.admin.stat_job_seekers': 'Total Job Seekers',
      'dashboard.admin.stat_employers': 'Total Employers',
      'dashboard.admin.stat_advertisers': 'Total Advertisers',
      'dashboard.admin.stat_active_jobs': 'Active Jobs',
      'dashboard.admin.stat_pending_approvals': 'Pending Approvals',
      'dashboard.admin.stat_placeholder': 'Placeholder',
      'dashboard.admin.admin_only': '(Admin Only)',
      'dashboard.admin.pending_jobs': 'Pending Job Approvals',
      'dashboard.admin.loading_jobs': 'Loading pending jobs...',
      'dashboard.admin.no_pending_jobs': 'No Pending Job Approvals',
      'dashboard.admin.pending_jobs_help': 'All job postings have been reviewed and approved. New job postings requiring approval will appear here.',
      'dashboard.admin.supabase_not_configured': 'Supabase is not configured yet. Showing placeholder data.',
      'dashboard.admin.table_job_title': 'Job Title',
      'dashboard.admin.table_company': 'Company',
      'dashboard.admin.table_category': 'Category',
      'dashboard.admin.table_location': 'Location',
      'dashboard.admin.table_posted_by': 'Posted By',
      'dashboard.admin.table_posted_at': 'Posted At',
      'dashboard.admin.table_status': 'Status',
      'dashboard.admin.table_actions': 'Actions',
      'dashboard.admin.button_approve': 'Approve',
      'dashboard.admin.button_featured': 'Featured',
      'dashboard.admin.tooltip_coming_phase2': 'Approval actions coming in Phase 2',
      'dashboard.admin.pending_orders': 'Pending Advertising Orders',
      'dashboard.admin.loading_orders': 'Loading pending advertising orders...',
      'dashboard.admin.no_pending_orders': 'No Pending Advertising Orders',
      'dashboard.admin.pending_orders_help': 'All advertising orders have been reviewed and approved. New advertising orders requiring approval will appear here.',
      'dashboard.admin.table_order_type': 'Order Type',
      'dashboard.admin.table_price': 'Price',
      'dashboard.admin.table_ordered_by': 'Ordered By',
      'dashboard.admin.table_created_at': 'Created At',
      'dashboard.admin.order_type_standard': 'Standard',
      'dashboard.admin.order_type_featured': 'Featured',
      'dashboard.admin.order_type_placement': 'Placement',
      'dashboard.admin.user_management': 'User Management',
      'dashboard.admin.button_export_users': 'Export User Report',
      'dashboard.admin.admin_header': 'User Administration',
      'dashboard.admin.admin_help': 'Administrative user controls and management tools will be available here.',
      'dashboard.admin.button_search_users': 'Search Users',
      'dashboard.admin.button_manage_roles': 'Manage Roles',
      'dashboard.admin.button_user_activity': 'View User Activity',
      'dashboard.admin.button_suspend_users': 'Suspend/Ban Users',
      'dashboard.admin.system_logs': 'System Logs',
      'dashboard.admin.logs_placeholder': 'System activity logs placeholder',
      'dashboard.admin.button_download_logs': 'Download Logs',
      'dashboard.admin.logs_help1': 'System logs and activity records will be displayed here.',
      'dashboard.admin.logs_help2': 'This will include user activities, administrative actions, and system events.',

      // Dashboard Redirect Page
      'dashboard.redirect.loading_dashboard': 'Loading Dashboard...',
      'dashboard.redirect.determining_role': 'Determining your role and redirecting you to your dashboard.',

      // Component Messages
      'component.header.logout': 'Logout',
      'component.header.welcome': 'Welcome,',
      'component.protected_route.verifying': 'Verifying authentication...',
      'component.protected_route.access_denied': 'Access Denied',
      'component.protected_route.signin_required': 'You need to be signed in to access this page.',
      'component.protected_route.redirecting': 'Redirecting you to sign in...',
      'component.role_gate.access_restricted': 'Access Restricted',
      'component.role_gate.no_permission': 'You don\'t have permission to view this content.',
      'component.role_gate.contact_support': 'Contact support if you believe this is an error.',
      'component.role_gate.employer_feature_title': 'Employer Feature',
      'component.role_gate.employer_feature_desc': 'This feature is available for employer accounts only.',
      'component.role_gate.admin_only_title': 'Administrator Only',
      'component.role_gate.admin_only_desc': 'This feature is restricted to administrators.',
      'component.dashboard.loading_dashboard': 'Loading Dashboard...',
      'component.dashboard.determining_role': 'Determining your role and redirecting you to your dashboard.',
      'component.dashboard.account_type': 'Account Type',

      // Auth Service Messages
      'auth.error_all_fields_required': 'All fields are required: email, password, firstName, lastName, role',
      'auth.error_invalid_role': 'Invalid role. Must be one of: job_seeker, employer, advertiser',
      'auth.error_unexpected_signup': 'An unexpected error occurred during signup',
      'auth.error_email_password_required': 'Email and password are required',
      'auth.error_unexpected_login': 'An unexpected error occurred during login',
      'auth.error_unexpected_logout': 'An unexpected error occurred during logout',
      'auth.error_unexpected_get_user': 'An unexpected error occurred while fetching current user',
      'auth.error_user_id_required': 'userId is required',
      'auth.error_user_not_found': 'User not found',
      'auth.error_unexpected_get_role': 'An unexpected error occurred while fetching user role',

      // Job Posting Service Messages
      'jobPosting.error_job_data_required': 'Job data is required',
      'jobPosting.error_user_id_required': 'User ID is required to post a job',
      'jobPosting.error_title_required': 'Job title is required and must be at least 3 characters long',
      'jobPosting.error_company_required': 'Company name is required',
      'jobPosting.error_category_required': 'Job category is required',
      'jobPosting.error_city_required': 'City is required',
      'jobPosting.error_state_required': 'State is required',
      'jobPosting.error_state_invalid': 'State must be a valid US state abbreviation (e.g., CA, NY, TX)',
      'jobPosting.error_description_required': 'Job description is required and must be at least 20 characters long',
      'jobPosting.error_email_required': 'Contact email is required',
      'jobPosting.error_email_invalid': 'Contact email must be a valid email address',
      'jobPosting.error_mason_attestation_required': 'Mason in Good Standing self-attestation is required to post',
      'jobPosting.error_compensation_format': 'Compensation range must be in format: $50,000 - $75,000 or similar',
      'jobPosting.error_unexpected': 'An unexpected error occurred while posting the job',

      // Stripe Checkout Messages
      'stripe.error_missing_parameters': 'Missing required parameters: productType, userId, and itemId',
      'stripe.error_not_configured': 'Stripe is not configured yet',
      'stripe.error_invalid_product_type': 'Invalid productType',
      'stripe.error_create_session_failed': 'Failed to create checkout session',
      'stripe.error_no_session_id': 'No session ID returned from server',
      'stripe.error_redirect_failed': 'Failed to redirect to checkout',
      'stripe.error_unexpected': 'An unexpected error occurred',

      // Admin Service Messages
      'admin.error_job_id_required': 'Job ID is required',
      'admin.error_order_id_required': 'Order ID is required',
      'admin.error_unexpected_pending_jobs': 'An unexpected error occurred while fetching pending jobs',
      'admin.error_unexpected_pending_orders': 'An unexpected error occurred while fetching pending advertising orders',
      'admin.error_unexpected_approve_job': 'An unexpected error occurred while approving the job',
      'admin.error_unexpected_featured_status': 'An unexpected error occurred while updating featured status',
      'admin.error_unexpected_approve_order': 'An unexpected error occurred while approving the advertising order',

      // Post Job Page Messages
      'page.post_job.must_be_logged_in': 'Please sign in as an employer to post a job.',
      'page.post_job.login_prompt_description': 'To post job openings and connect with qualified candidates in the Masonic community, you need to create an employer account or sign in.',
      'page.post_job.sign_in_button': 'Sign In',
      'page.post_job.create_account_button': 'Create Employer Account',
      'page.post_job.access_denied': 'Access Denied',
      'page.post_job.employer_only': 'This page is for employers only. Please sign in with an employer account or create a new employer account.',
      'page.post_job.return_dashboard': 'Return to Dashboard',
      'page.post_job.job_posted_success': 'Your job has been submitted and is pending review.',
      'page.post_job.missing_user_or_job_id': 'User information or job ID is missing',
      'page.post_job.featured_badge': 'FEATURED',
      'page.post_job.duration': '30 days',

      // Advertising Page Messages
      'page.advertising.must_be_logged_in': 'You must be logged in to purchase advertising',
      'page.advertising.price': '$199',
      'page.advertising.processing_button': 'Processing...',
      'page.advertising.featured_badge': 'FEATURED',

      // Button and Common Terms
      'common.yes': 'Yes',
      'common.no': 'No',
      'common.ok': 'OK',
      'common.cancel': 'Cancel',
      'common.submit': 'Submit',
      'common.back': 'Back',
      'common.next': 'Next',
      'common.save': 'Save',
      'common.delete': 'Delete',
      'common.edit': 'Edit',
      'common.close': 'Close',
      'common.loading': 'Loading...',
      'common.error': 'Error',
      'common.success': 'Success',
      'common.warning': 'Warning',
      'common.info': 'Information',
    },
    es: {
      // Navigation
      'nav.home': 'Inicio',
      'nav.find_jobs': 'Buscar Empleos',
      'nav.traveling_man': 'Viajero Masón',
      'nav.post_job': 'Publicar un Empleo',
      'nav.advertising': 'Publicidad',
      'nav.signin': 'Iniciar Sesión',
      'nav.register': 'Registrarse',

      // Footer
      'footer.quick_links': 'Enlaces Rápidos',
      'footer.legal': 'Legal',
      'footer.terms': 'Términos de Servicio',
      'footer.privacy': 'Política de Privacidad',
      'footer.all_rights': 'Todos los derechos reservados.',
      'footer.tagline': 'Construyendo Carreras. Fortaleciendo la Hermandad.',

      // Find Jobs Page
      'page.find_jobs.title': 'Buscar Empleos',
      'page.find_jobs.subtitle': 'Descubre Oportunidades en la Comunidad Masónica',
      'page.find_jobs.description': 'Busca empleos de empleadores amigos de la masonería en todo Estados Unidos. Filtra por ubicación, tipo de trabajo y tus preferencias.',
      'page.find_jobs.filter.keyword': 'Palabra Clave',
      'page.find_jobs.filter.category': 'Categoría',
      'page.find_jobs.filter.state': 'Estado',
      'page.find_jobs.filter.remote': 'Trabajo Remoto',
      'page.find_jobs.filter.traveling_man': 'Empleos de Viajero Masón',
      'page.find_jobs.search_button': 'Buscar Empleos',
      'page.find_jobs.no_jobs': 'No se encontraron empleos. Intenta ajustar tus filtros.',

      // Traveling Man Page
      'page.traveling_man.title': 'Empleos para Viajero Masón',
      'page.traveling_man.subtitle': 'Oportunidades de Reubicación y Viaje',
      'page.traveling_man.description': 'Explora oportunidades de trabajo diseñadas para Masones que viajan o están dispuestos a reubicarse. Perfecto para aquellos que buscan nuevas experiencias en todo el país.',
      'page.traveling_man.job_card': 'Oportunidad de Empleo',
      'page.traveling_man.location': 'Ubicación',
      'page.traveling_man.type': 'Tipo de Empleo',
      'page.traveling_man.view_details': 'Ver Detalles',

      // Post Job Page
      'page.post_job.title': 'Publicar un Empleo',
      'page.post_job.subtitle': 'Conecta con Candidatos Calificados Masónicos',
      'page.post_job.description': 'Publica tu oferta de trabajo y conecta con profesionales calificados en la comunidad masónica.',
      'page.post_job.form.title': 'Título del Empleo',
      'page.post_job.form.description': 'Descripción del Empleo',
      'page.post_job.form.requirements': 'Requisitos',
      'page.post_job.form.location': 'Ubicación',
      'page.post_job.form.remote': 'Trabajo Remoto Disponible',
      'page.post_job.form.traveling_man': 'Oportunidad de Viajero Masón',
      'page.post_job.form.compensation': 'Rango de Compensación',
      'page.post_job.form.masonic_friendly': 'Empleador Amigo de la Masonería',
      'page.post_job.form.self_attested': 'Afirmo que soy un Masón en Buena Condición',
      'page.post_job.submit': 'Publicar Empleo',
      'page.post_job.pricing_note': 'Listado estándar: Gratis | Listado destacado: Función premium',

      // Advertising Page
      'page.advertising.title': 'Publicidad',
      'page.advertising.subtitle': 'Promueve tu Negocio ante Profesionales Masónicos',
      'page.advertising.description': 'Anuncia tus productos, servicios o negocio a nuestra comunidad comprometida de Masones y empleadores amigos de la masonería.',
      'page.advertising.option1.title': 'Listado Estándar',
      'page.advertising.option1.description': 'Colocación de anuncio básica',
      'page.advertising.option1.price': 'Contacta para precios',
      'page.advertising.option2.title': 'Listado Destacado',
      'page.advertising.option2.description': 'Colocación de visibilidad premium',
      'page.advertising.option2.price': 'Precios premium',
      'page.advertising.option3.title': 'Colocación de Publicidad',
      'page.advertising.option3.description': 'Opciones de publicidad personalizadas',
      'page.advertising.option3.price': 'Precios personalizados',
      'page.advertising.learn_more': 'Más Información',

      // Sign In Page
      'page.signin.title': 'Iniciar Sesión',
      'page.signin.subtitle': 'Accede a tu Cuenta de 357NETWORK',
      'page.signin.form.email': 'Correo Electrónico',
      'page.signin.form.password': 'Contraseña',
      'page.signin.form.remember': 'Recuérdame',
      'page.signin.form.forgot_password': '¿Olvidaste tu contraseña?',
      'page.signin.submit': 'Iniciar Sesión',
      'page.signin.no_account': '¿No tienes cuenta?',
      'page.signin.create_account': 'Crea una',

      // Register Page
      'page.register.title': 'Crear Cuenta',
      'page.register.subtitle': 'Únete a la Comunidad 357NETWORK',
      'page.register.role_selection': 'Soy un/a:',
      'page.register.role.job_seeker': 'Buscador de Empleo',
      'page.register.role.employer': 'Empleador',
      'page.register.role.advertiser': 'Publicista',
      'page.register.form.email': 'Correo Electrónico',
      'page.register.form.password': 'Contraseña',
      'page.register.form.confirm_password': 'Confirmar Contraseña',
      'page.register.form.name': 'Nombre Completo',
      'page.register.form.company': 'Nombre de la Empresa',
      'page.register.form.terms': 'Acepto los Términos de Servicio',
      'page.register.submit': 'Crear Cuenta',
      'page.register.have_account': '¿Ya tienes cuenta?',
      'page.register.sign_in': 'Iniciar sesión',

      // Terms Page
      'page.terms.title': 'Términos de Servicio',
      'page.terms.lastUpdated': 'Última actualización:',
      'page.terms.section1.title': '1. Acuerdo de Términos',
      'page.terms.section1.content': 'Al acceder y usar 357NETWORK, aceptas y estás de acuerdo en ser vinculado por los términos y disposiciones de este acuerdo.',
      'page.terms.section2.title': '2. Licencia de Uso',
      'page.terms.section2.content': 'Se otorga permiso para descargar temporalmente una copia de los materiales (información o software) en 357NETWORK solo para visualización personal y no comercial.',
      'page.terms.section3.title': '3. Descargo de Responsabilidad',
      'page.terms.section3.content': 'Los materiales en 357NETWORK se proporcionan tal cual. 357NETWORK no ofrece garantías, expresas o implícitas, y por este medio renuncia y niega todas las demás garantías, incluidas, entre otras, las garantías implícitas de comerciabilidad, aptitud para un propósito particular o no infracción de derechos de propiedad intelectual.',
      'page.terms.section4.title': '4. Limitaciones',
      'page.terms.section4.content': 'En ningún caso 357NETWORK o sus proveedores serán responsables de ningún daño (incluidos, entre otros, daños por pérdida de datos o ganancias, o debido a interrupción del negocio) resultante del uso o la incapacidad de usar los materiales en 357NETWORK.',

      // Privacy Page
      'page.privacy.title': 'Política de Privacidad',
      'page.privacy.lastUpdated': 'Última actualización:',
      'page.privacy.subtitle': 'Cómo Protegemos tus Datos',
      'page.privacy.section1_title': '1. Información que Recopilamos',
      'page.privacy.section1_content': 'Recopilamos información que proporcionas directamente, como cuando creas una cuenta, publicas un trabajo o nos contactas. Esto puede incluir tu nombre, correo electrónico, número de teléfono, ubicación e información profesional.',
      'page.privacy.section2_title': '2. Cómo Utilizamos tu Información',
      'page.privacy.section2_content': 'Usamos la información recopilada para proporcionar, mantener y mejorar nuestros servicios, procesar transacciones y comunicarnos contigo sobre actualizaciones y cambios en nuestro servicio.',
      'page.privacy.section3_title': '3. Intercambio de Información',
      'page.privacy.section3_content': 'No vendemos ni alquilamos tu información personal a terceros. Podemos compartir información según lo requiera la ley o para proteger los derechos y la seguridad de nuestros usuarios y el público.',
      'page.privacy.section4_title': '4. Seguridad de Datos',
      'page.privacy.section4_content': 'Implementamos medidas técnicas y organizativas apropiadas diseñadas para proteger la información personal contra acceso no autorizado, alteración, divulgación o destrucción.',
      'page.privacy.section5_title': '5. Tus Derechos',
      'page.privacy.section5_content': 'Tienes derecho a acceder, actualizar o eliminar tu información personal en cualquier momento poniéndote en contacto con nosotros.',
      'page.privacy.section6_title': '6. Cookies y Rastreo',
      'page.privacy.section6_content': 'Utilizamos cookies y tecnologías de rastreo similares para mejorar tu experiencia. Puedes controlar la configuración de cookies a través de las preferencias de tu navegador.',
      'page.privacy.section7_title': '7. Enlaces de Terceros',
      'page.privacy.section7_content': 'Nuestro sitio web puede contener enlaces a sitios web de terceros. No somos responsables de las prácticas de privacidad de esos sitios. Te recomendamos que revises sus políticas de privacidad.',
      'page.privacy.section8_title': '8. Cambios de Política',
      'page.privacy.section8_content': 'Podemos actualizar esta política de privacidad periódicamente. Te notificaremos sobre cambios significativos actualizando la fecha de última actualización y buscando tu consentimiento si lo requiere la ley.',
      'page.privacy.contact_title': 'Contáctanos',
      'page.privacy.contact_content': 'Si tienes preguntas sobre esta política de privacidad o nuestras prácticas de datos, contáctanos en:',

      // Home Page
      'page.home.welcome_title': 'Bienvenido a 357NETWORK',
      'page.home.welcome_description': 'Una red profesional de empleo para Masones, empleadores amigos de la masonería y buscadores de trabajo.',
      'page.home.tagline_secondary': 'Construyendo Carreras. Fortaleciendo la Hermandad.',
      'page.home.button_find_jobs': 'Buscar Empleos',
      'page.home.button_post_job': 'Publicar un Empleo',
      'page.home.card_job_seekers_title': 'Para Buscadores de Empleo',
      'page.home.card_job_seekers_description': 'Descubre oportunidades con empleadores amigos de la masonería y conecta con la comunidad.',
      'page.home.card_employers_title': 'Para Empleadores',
      'page.home.card_employers_description': 'Publica ofertas de trabajo y alcanza candidatos calificados que comparten valores masónicos.',
      'page.home.card_traveling_title': 'Viajero Masón',
      'page.home.card_traveling_description': 'Oportunidades especiales para Masones que buscan trabajo temporal o remoto en todo Estados Unidos.',
      'page.home.placeholder_note': 'Marcador de Fase 1 - Próximos: Navegación, Búsqueda de Empleos, Paneles de Control de Usuarios y Más',

      // Find Jobs Page - Additional
      'page.find_jobs.search_title': 'Buscar y Filtrar',
      'page.find_jobs.available_jobs': 'Empleos Disponibles',
      'page.find_jobs.loading': 'Cargando empleos...',
      'page.find_jobs.error': 'Error al cargar empleos',
      'page.find_jobs.no_jobs_description': 'Vuelve pronto para nuevas oportunidades, o ajusta tus filtros de búsqueda.',
      'page.find_jobs.all_categories': 'Todas las Categorías',
      'page.find_jobs.category_skilled_trades': 'Oficios Especializados',
      'page.find_jobs.category_construction': 'Construcción',
      'page.find_jobs.category_technology': 'Tecnología',
      'page.find_jobs.category_sales': 'Ventas',
      'page.find_jobs.category_healthcare': 'Salud',
      'page.find_jobs.all_states': 'Todos los Estados',
      'page.find_jobs.job_title_placeholder': 'Marcador de Título de Empleo',
      'page.find_jobs.company_name': 'Nombre de la Empresa',
      'page.find_jobs.city_state': 'Ciudad, Estado',
      'page.find_jobs.job_description_placeholder': 'Descripción del empleo...',

      // Traveling Man Page - Additional
      'page.traveling_man.section_about_title': 'Acerca de los Empleos para Viajero Masón',
      'page.traveling_man.section_about_description': 'Las oportunidades de Viajero Masón son ideales para Masones que buscan trabajo temporal, reubicación o empleo basado en viajes. Estas posiciones ofrecen flexibilidad y la oportunidad de trabajar con empleadores amigos de la masonería en todo Estados Unidos.',
      'page.traveling_man.opportunities_title': 'Oportunidades de Viajero Masón',
      'page.traveling_man.badge_text': 'Viajero Masón',
      'page.traveling_man.project_title': 'Trabajo de Proyecto Temporal',
      'page.traveling_man.duration_3_6': 'Temporal (3-6 meses)',
      'page.traveling_man.relocation_support': 'Oportunidad de trabajo temporal con apoyo de reubicación...',
      'page.traveling_man.consulting_title': 'Consultoría Remota',
      'page.traveling_man.duration_flexible': 'Remoto Flexible',
      'page.traveling_man.consulting_description': 'Posición de consultoría amigable con viajes con horario flexible...',
      'page.traveling_man.seasonal_title': 'Contrato Estacional',
      'page.traveling_man.duration_seasonal': 'Contrato',
      'page.traveling_man.seasonal_description': 'Trabajo estacional con alojamiento de viajes proporcionado...',
      'page.traveling_man.multiple_states': 'Múltiples Estados',
      'page.traveling_man.seasonal_rotation': 'Rotación Estacional',

      // Post Job Page - Additional
      'page.post_job.form_title': 'Formulario de Publicación de Empleo',
      'page.post_job.job_title': 'Título del Empleo',
      'page.post_job.company_name': 'Nombre de la Empresa',
      'page.post_job.category': 'Categoría',
      'page.post_job.location': 'Ubicación',
      'page.post_job.job_description': 'Descripción del Empleo',
      'page.post_job.salary': 'Rango de Compensación',
      'page.post_job.requirements': 'Requisitos',
      'page.post_job.contact_email': 'Correo Electrónico de Contacto',
      'page.post_job.remote_position': 'Trabajo Remoto Disponible',
      'page.post_job.traveling_man_eligible': 'Oportunidad de Viajero Masón',
      'page.post_job.select_category': 'Selecciona una categoría...',
      'page.post_job.salary_placeholder': '$50,000 - $75,000',
      'page.post_job.requirements_placeholder': 'Habilidades y calificaciones requeridas (opcional)',
      'page.post_job.email_placeholder': 'contacto@ejemplo.com',
      'page.post_job.city_placeholder': 'Ciudad',
      'page.post_job.state_placeholder': 'CA',
      'page.post_job.submit_button': 'Publicar Empleo',
      'page.post_job.posting_button': 'Publicando...',
      'page.post_job.attestation_required': 'Se requiere auto-atestación de Masón en Buena Condición para publicar',
      'page.post_job.payment_section_title': 'Opciones de Pago',
      'page.post_job.payment_card_standard': 'Listado de Empleo Estándar',
      'page.post_job.payment_card_featured': 'Listado de Empleo Destacado',
      'page.post_job.payment_price_standard': '$29',
      'page.post_job.payment_price_featured': '$79',
      'page.post_job.payment_duration': 'por 30 días',
      'page.post_job.payment_button': 'Proceder al Pago',
      'page.post_job.payment_processing': 'Procesando...',
      'page.post_job.stripe_not_configured': 'El pago de Stripe aún no está configurado',
      'page.post_job.section_pricing': 'Precios de Publicación',
      'page.post_job.pricing_standard': 'Listado Estándar',
      'page.post_job.pricing_featured': 'Listado Destacado',
      'page.post_job.pricing_standard_desc': 'Publica tu empleo durante 30 días con visibilidad estándar en 357NETWORK.',
      'page.post_job.pricing_featured_desc': 'Visibilidad premium con colocación destacada en los resultados de búsqueda de empleo.',
      'page.post_job.error_login_required': 'Debes iniciar sesión para publicar un empleo',
      'page.post_job.error_payment_missing': 'Falta información del usuario o ID del empleo',

      // Advertising Page - Additional
      'page.advertising.choose_option': 'Elige tu Opción de Publicidad',
      'page.advertising.standard.title': 'Listado Estándar',
      'page.advertising.standard.duration': '30 días - $199',
      'page.advertising.standard.feature1': 'Colocación de anuncio básica',
      'page.advertising.standard.feature2': 'Visibilidad en la página de inicio',
      'page.advertising.standard.feature3': 'Acceso a la comunidad',
      'page.advertising.standard.feature4': 'Notificaciones por correo electrónico',
      'page.advertising.featured.title': 'Listado Destacado',
      'page.advertising.featured.duration': '30 días - $399',
      'page.advertising.featured.feature1': 'Visibilidad premium',
      'page.advertising.featured.feature2': 'Colocación destacada',
      'page.advertising.featured.feature3': 'Posición superior de la página',
      'page.advertising.featured.feature4': 'Notificaciones de correo electrónico prioritarias',
      'page.advertising.featured.feature5': 'Panel de análisis',
      'page.advertising.placement.title': 'Colocación de Publicidad',
      'page.advertising.placement.duration': '30 días - $199',
      'page.advertising.placement.feature1': 'Colocación personalizada de anuncios',
      'page.advertising.placement.feature2': 'Posicionamiento flexible',
      'page.advertising.placement.feature3': 'Alcance comunitario',
      'page.advertising.placement.feature4': 'Soporte estándar',
      'page.advertising.choose_button': 'Elegir Esta Opción',
      'page.advertising.how_it_works': 'Cómo Funciona',
      'page.advertising.step1.title': 'Selecciona tu Opción',
      'page.advertising.step1.description': 'Elige la opción de publicidad que mejor se ajuste a tus necesidades y presupuesto.',
      'page.advertising.step2.title': 'Proporciona tu Contenido',
      'page.advertising.step2.description': 'Envía el contenido de tu anuncio, imágenes y preferencias de orientación.',
      'page.advertising.step3.title': 'Pagar',
      'page.advertising.step3.description': 'Completa el proceso de pago de forma segura a través de nuestra plataforma.',
      'page.advertising.step4.title': 'Ir En Vivo',
      'page.advertising.step4.description': 'Tu anuncio se publica y llega a la comunidad 357NETWORK.',
      'page.advertising.error_login_required': 'Debes iniciar sesión para comprar publicidad',

      // Sign In Page - Additional
      'page.signin.form_title': 'Ingresa tus Credenciales',
      'page.signin.email': 'Correo Electrónico',
      'page.signin.email_placeholder': 'tu@correo.com',
      'page.signin.password': 'Contraseña',
      'page.signin.password_placeholder': 'Ingresa tu contraseña',
      'page.signin.remember_me': 'Recuérdame',
      'page.signin.submit_button': 'Iniciar Sesión',
      'page.signin.forgot_password': '¿Olvidaste tu contraseña?',
      'page.signin.reset_link': 'Restáblecela aquí',
      'page.signin.signup_link': 'Regístrate aquí',
      'page.signin.benefits_title': 'Beneficios de 357NETWORK',
      'page.signin.benefit1_title': 'Conecta con Masones',
      'page.signin.benefit1_description': 'Conecta con otros Masones Libres en tu profesión y comunidad.',
      'page.signin.benefit2_title': 'Encuentra Empleos de Calidad',
      'page.signin.benefit2_description': 'Accede a oportunidades de empleo de empleadores amigos de la masonería.',
      'page.signin.benefit3_title': 'Desarrolla tu Carrera',
      'page.signin.benefit3_description': 'Avanza tus objetivos profesionales dentro de la hermandad masónica.',
      'page.signin.error_required_fields': 'Se requieren correo electrónico y contraseña',
      'page.signin.error_login_failed': 'El inicio de sesión falló. Por favor, intenta de nuevo.',

      // Register Page - Additional
      'page.register.form_title': 'Información de la Cuenta',
      'page.register.account_type': 'Soy un/a:',
      'page.register.job_seeker': 'Buscador de Empleo',
      'page.register.job_seeker_description': 'Buscando oportunidades de empleo',
      'page.register.employer': 'Empleador',
      'page.register.employer_description': 'Contratando candidatos calificados',
      'page.register.advertiser': 'Publicista',
      'page.register.advertiser_description': 'Promoviendo productos y servicios',
      'page.register.first_name': 'Nombre',
      'page.register.last_name': 'Apellido',
      'page.register.email': 'Correo Electrónico',
      'page.register.email_placeholder': 'tu@correo.com',
      'page.register.password': 'Contraseña',
      'page.register.password_placeholder': 'Al menos 8 caracteres',
      'page.register.confirm_password': 'Confirmar Contraseña',
      'page.register.confirm_password_placeholder': 'Vuelve a ingresar tu contraseña',
      'page.register.agree_terms': 'Estoy de acuerdo con los',
      'page.register.terms_link': 'Términos de Servicio',
      'page.register.submit_button': 'Crear Cuenta',
      'page.register.submitting': 'Creando Cuenta',
      'page.register.signin_link': 'Inicia sesión en su lugar',
      'page.register.error_all_fields_required': 'Todos los campos son obligatorios',
      'page.register.error_invalid_email': 'Por favor, ingresa una dirección de correo válida',
      'page.register.error_password_length': 'La contraseña debe tener al menos 8 caracteres',
      'page.register.error_password_mismatch': 'Las contraseñas no coinciden',
      'page.register.error_role_required': 'Por favor, selecciona un tipo de cuenta',
      'page.register.error_terms_required': 'Debes aceptar los términos y condiciones',
      'page.register.error_signup_failed': 'El registro falló. Por favor, intenta de nuevo.',

      // Terms Page - Additional
      'page.terms.subtitle': 'Comprendiendo Nuestro Acuerdo de Servicio',
      'page.terms.section1_title': '1. Acuerdo de Términos',
      'page.terms.section1_content': 'Al acceder y usar 357NETWORK, aceptas y estás de acuerdo en ser vinculado por los términos y disposiciones de este acuerdo.',
      'page.terms.section2_title': '2. Licencia de Uso',
      'page.terms.section2_content': 'Se otorga permiso para descargar temporalmente una copia de los materiales (información o software) en 357NETWORK solo para visualización personal no comercial.',
      'page.terms.section3_title': '3. Descargo de Responsabilidad',
      'page.terms.section3_content': 'Los materiales en 357NETWORK se proporcionan tal cual. 357NETWORK no ofrece garantías, expresas o implícitas, y por este medio renuncia y niega todas las demás garantías, incluidas, entre otras, las garantías implícitas de comerciabilidad, aptitud para un propósito particular o no infracción de derechos de propiedad intelectual.',
      'page.terms.section4_title': '4. Limitaciones',
      'page.terms.section4_content': 'En ningún caso 357NETWORK o sus proveedores serán responsables de ningún daño (incluidos, entre otros, daños por pérdida de datos o ganancias, o debido a interrupción del negocio) resultante del uso o la incapacidad de usar los materiales en 357NETWORK.',
      'page.terms.section5_title': '5. Precisión de Materiales',
      'page.terms.section5_content': 'Los materiales que aparecen en 357NETWORK podrían incluir errores técnicos, tipográficos o fotográficos. 357NETWORK no garantiza que ninguno de los materiales en su sitio web sean precisos, completos o actuales.',
      'page.terms.section6_title': '6. Enlaces',
      'page.terms.section6_content': '357NETWORK no ha revisado todos los sitios vinculados a su sitio web y no es responsable del contenido de ningún sitio vinculado. La inclusión de cualquier enlace no implica aprobación de 357NETWORK del sitio. El uso de cualquier sitio web vinculado es por tu propia cuenta y riesgo.',
      'page.terms.section7_title': '7. Modificaciones',
      'page.terms.section7_content': '357NETWORK puede revisar estos términos de servicio de su sitio web en cualquier momento sin aviso. Al usar este sitio web, estás aceptando estar vinculado por la versión actual de estos términos de servicio.',
      'page.terms.section8_title': '8. Ley Aplicable',
      'page.terms.section8_content': 'Estos términos y condiciones se rigen por las leyes de Estados Unidos, y aceptas irrevocablemente la jurisdicción exclusiva de los tribunales en esa ubicación.',
      'page.terms.contact_title': 'Información de Contacto',
      'page.terms.contact_content': 'Si tienes preguntas sobre estos términos de servicio, contáctanos en:',

      // Dashboard Pages
      'dashboard.job_seeker.title': 'Panel de Control del Buscador de Empleo',
      'dashboard.job_seeker.subtitle': 'Bienvenido a tu centro de carrera',
      'dashboard.job_seeker.profile_summary': 'Resumen del Perfil',
      'dashboard.job_seeker.welcome_message': '¡Bienvenido, Buscador de Empleo!',
      'dashboard.job_seeker.profile_help': 'Tu perfil ayuda a los empleadores a encontrarte. Completa tu perfil para aumentar tu visibilidad y coincidir con más oportunidades de empleo.',
      'dashboard.job_seeker.full_name': 'Nombre Completo',
      'dashboard.job_seeker.full_name_placeholder': 'Tu nombre',
      'dashboard.job_seeker.professional_title': 'Título Profesional',
      'dashboard.job_seeker.professional_title_placeholder': 'Tu título profesional',
      'dashboard.job_seeker.location': 'Ubicación',
      'dashboard.job_seeker.location_placeholder': 'Ciudad, Estado',
      'dashboard.job_seeker.bio': 'Biografía',
      'dashboard.job_seeker.bio_placeholder': 'Cuéntale a los empleadores sobre ti',
      'dashboard.job_seeker.button_update_profile': 'Actualizar Perfil',
      'dashboard.job_seeker.saved_jobs': 'Empleos Guardados',
      'dashboard.job_seeker.no_saved_jobs': 'Sin Empleos Guardados Aún',
      'dashboard.job_seeker.saved_jobs_help': 'Comienza a guardar empleos de los listados de empleos para verlos aquí. Los empleos guardados te ayudan a realizar un seguimiento de las oportunidades que te interesan.',
      'dashboard.job_seeker.button_browse_jobs': 'Explorar Empleos',
      'dashboard.job_seeker.applications_history': 'Historial de Solicitudes',
      'dashboard.job_seeker.no_applications': 'Sin Solicitudes Aún',
      'dashboard.job_seeker.applications_help': 'Las solicitudes que envíes a los listados de empleos aparecerán aquí. Realiza un seguimiento del estado de tu solicitud y los próximos pasos.',
      'dashboard.job_seeker.button_view_jobs': 'Ver Empleos',
      'dashboard.job_seeker.recommended_jobs': 'Empleos Recomendados',
      'dashboard.job_seeker.no_recommendations': 'Sin Recomendaciones Aún',
      'dashboard.job_seeker.recommendations_help': 'Completa tu perfil para recibir recomendaciones de empleo personalizadas que coincidan con tus habilidades y preferencias.',
      'dashboard.job_seeker.button_complete_profile': 'Completar Perfil',

      'dashboard.employer.title': 'Panel de Control del Empleador',
      'dashboard.employer.subtitle': 'Administra tus publicaciones de empleo y solicitudes',
      'dashboard.employer.company_profile': 'Resumen del Perfil de la Empresa',
      'dashboard.employer.company_info': 'Información de la Empresa',
      'dashboard.employer.company_info_help': 'Mantén tu perfil de empresa para atraer candidatos calificados y proporcionarles información sobre tu organización.',
      'dashboard.employer.company_name': 'Nombre de la Empresa',
      'dashboard.employer.company_name_placeholder': 'Nombre de tu empresa',
      'dashboard.employer.company_website': 'Sitio Web de la Empresa',
      'dashboard.employer.company_website_placeholder': 'https://tuempresa.com',
      'dashboard.employer.location': 'Ubicación',
      'dashboard.employer.location_placeholder': 'Ciudad, Estado',
      'dashboard.employer.company_description': 'Descripción de la Empresa',
      'dashboard.employer.company_description_placeholder': 'Cuéntale a los buscadores de empleo sobre tu empresa',
      'dashboard.employer.masonic_status': 'Estado Amigo de la Masonería',
      'dashboard.employer.masonic_select': 'Seleccionar estado',
      'dashboard.employer.masonic_yes': 'Sí, somos amigos de la masonería',
      'dashboard.employer.masonic_no': 'No, no aplica',
      'dashboard.employer.button_update_company': 'Actualizar Perfil de la Empresa',
      'dashboard.employer.posted_jobs': 'Empleos Publicados',
      'dashboard.employer.button_post_new_job': 'Publicar un Nuevo Empleo',
      'dashboard.employer.no_posted_jobs': 'Sin Empleos Publicados Aún',
      'dashboard.employer.posted_jobs_help': 'No has publicado ningún empleo aún. Comienza publicando tu primera oferta de empleo para conectar con candidatos calificados.',
      'dashboard.employer.button_create_job': 'Crear Publicación de Empleo',
      'dashboard.employer.job_applications': 'Solicitudes de Empleo',
      'dashboard.employer.no_applications': 'Sin Solicitudes Aún',
      'dashboard.employer.applications_help': 'Las solicitudes de los buscadores de empleo aparecerán aquí. Podrás revisar, enviar mensajes y administrar candidatos.',
      'dashboard.employer.button_view_applications': 'Ver Todas las Solicitudes',
      'dashboard.employer.billing_subscriptions': 'Facturación y Suscripciones',
      'dashboard.employer.subscription_status': 'Estado de la Suscripción',
      'dashboard.employer.billing_help1': 'La información de facturación y los detalles de la suscripción aparecerán aquí.',
      'dashboard.employer.billing_help2': 'Administra tu nivel de cuenta, actualiza funciones y ve el historial de facturas.',
      'dashboard.employer.button_manage_subscription': 'Administrar Suscripción',
      'dashboard.employer.button_view_invoices': 'Ver Facturas',

      'dashboard.advertiser.title': 'Panel de Control del Anunciante',
      'dashboard.advertiser.subtitle': 'Administra tus anuncios y campañas',
      'dashboard.advertiser.active_ads': 'Anuncios Activos',
      'dashboard.advertiser.button_create_ad': 'Crear Nuevo Anuncio',
      'dashboard.advertiser.no_active_ads': 'Sin Anuncios Activos',
      'dashboard.advertiser.ads_help': 'Aún no has creado ningún anuncio. Comienza creando tu primer anuncio para llegar a la comunidad 357NETWORK.',
      'dashboard.advertiser.campaign_performance': 'Rendimiento de la Campaña',
      'dashboard.advertiser.performance_metrics': 'Métricas de Rendimiento',
      'dashboard.advertiser.metrics_help': 'Los datos de rendimiento de la campaña se mostrarán aquí.',
      'dashboard.advertiser.total_impressions': 'Impresiones Totales',
      'dashboard.advertiser.total_clicks': 'Clics Totales',
      'dashboard.advertiser.click_through_rate': 'Tasa de Clics',
      'dashboard.advertiser.conversion_rate': 'Tasa de Conversión',
      'dashboard.advertiser.button_detailed_analytics': 'Ver Análisis Detallados',
      'dashboard.advertiser.billing_subscriptions': 'Facturación y Suscripciones',
      'dashboard.advertiser.advertising_account': 'Cuenta de Publicidad',
      'dashboard.advertiser.billing_help1': 'Administra tu presupuesto de publicidad, método de pago e historial de facturación.',
      'dashboard.advertiser.billing_help2': 'Actualiza tu suscripción para desbloquear funciones de publicidad premium.',
      'dashboard.advertiser.button_manage_billing': 'Administrar Facturación',
      'dashboard.advertiser.button_view_invoices': 'Ver Facturas',
      'dashboard.advertiser.ad_settings': 'Configuración de Anuncios',
      'dashboard.advertiser.ad_preferences': 'Preferencias de Publicidad',
      'dashboard.advertiser.business_name': 'Nombre del Negocio',
      'dashboard.advertiser.business_name_placeholder': 'Nombre de tu negocio',
      'dashboard.advertiser.business_website': 'Sitio Web del Negocio',
      'dashboard.advertiser.business_website_placeholder': 'https://tunegocio.com',
      'dashboard.advertiser.ad_category': 'Categoría Primaria de Anuncios',
      'dashboard.advertiser.category_select': 'Seleccionar categoría',
      'dashboard.advertiser.category_products': 'Productos y Servicios',
      'dashboard.advertiser.category_professional': 'Servicios Profesionales',
      'dashboard.advertiser.category_events': 'Eventos y Patrocinio',
      'dashboard.advertiser.category_other': 'Otro',
      'dashboard.advertiser.business_description': 'Descripción del Negocio',
      'dashboard.advertiser.business_description_placeholder': 'Describe tu negocio y lo que estás publicitando',
      'dashboard.advertiser.masonic_friendly': 'Negocio Amigo de la Masonería',
      'dashboard.advertiser.button_save_settings': 'Guardar Configuración',

      'dashboard.admin.title': 'Panel de Control de Admin - Aprobaciones',
      'dashboard.admin.subtitle': 'Administración del sistema y moderación de contenido',
      'dashboard.admin.statistics': 'Estadísticas del Sistema',
      'dashboard.admin.stat_total_users': 'Usuarios Totales',
      'dashboard.admin.stat_job_seekers': 'Total de Buscadores de Empleo',
      'dashboard.admin.stat_employers': 'Total de Empleadores',
      'dashboard.admin.stat_advertisers': 'Total de Anunciantes',
      'dashboard.admin.stat_active_jobs': 'Empleos Activos',
      'dashboard.admin.stat_pending_approvals': 'Aprobaciones Pendientes',
      'dashboard.admin.stat_placeholder': 'Marcador de posición',
      'dashboard.admin.admin_only': '(Solo Admin)',
      'dashboard.admin.pending_jobs': 'Aprobaciones de Empleo Pendientes',
      'dashboard.admin.loading_jobs': 'Cargando empleos pendientes...',
      'dashboard.admin.no_pending_jobs': 'Sin Aprobaciones de Empleo Pendientes',
      'dashboard.admin.pending_jobs_help': 'Todas las publicaciones de empleo han sido revisadas y aprobadas. Las nuevas publicaciones de empleo que requieran aprobación aparecerán aquí.',
      'dashboard.admin.supabase_not_configured': 'Supabase aún no está configurado. Mostrando datos de marcador de posición.',
      'dashboard.admin.table_job_title': 'Título del Empleo',
      'dashboard.admin.table_company': 'Empresa',
      'dashboard.admin.table_category': 'Categoría',
      'dashboard.admin.table_location': 'Ubicación',
      'dashboard.admin.table_posted_by': 'Publicado por',
      'dashboard.admin.table_posted_at': 'Publicado el',
      'dashboard.admin.table_status': 'Estado',
      'dashboard.admin.table_actions': 'Acciones',
      'dashboard.admin.button_approve': 'Aprobar',
      'dashboard.admin.button_featured': 'Destacado',
      'dashboard.admin.tooltip_coming_phase2': 'Las acciones de aprobación vendrán en la Fase 2',
      'dashboard.admin.pending_orders': 'Pedidos de Publicidad Pendientes',
      'dashboard.admin.loading_orders': 'Cargando pedidos de publicidad pendientes...',
      'dashboard.admin.no_pending_orders': 'Sin Pedidos de Publicidad Pendientes',
      'dashboard.admin.pending_orders_help': 'Todos los pedidos de publicidad han sido revisados y aprobados. Los nuevos pedidos de publicidad que requieran aprobación aparecerán aquí.',
      'dashboard.admin.table_order_type': 'Tipo de Pedido',
      'dashboard.admin.table_price': 'Precio',
      'dashboard.admin.table_ordered_by': 'Ordenado por',
      'dashboard.admin.table_created_at': 'Creado el',
      'dashboard.admin.order_type_standard': 'Estándar',
      'dashboard.admin.order_type_featured': 'Destacado',
      'dashboard.admin.order_type_placement': 'Colocación',
      'dashboard.admin.user_management': 'Administración de Usuarios',
      'dashboard.admin.button_export_users': 'Exportar Informe de Usuarios',
      'dashboard.admin.admin_header': 'Administración de Usuarios',
      'dashboard.admin.admin_help': 'Las herramientas de administración y control de usuarios estarán disponibles aquí.',
      'dashboard.admin.button_search_users': 'Buscar Usuarios',
      'dashboard.admin.button_manage_roles': 'Administrar Roles',
      'dashboard.admin.button_user_activity': 'Ver Actividad de Usuarios',
      'dashboard.admin.button_suspend_users': 'Suspender/Bloquear Usuarios',
      'dashboard.admin.system_logs': 'Registros del Sistema',
      'dashboard.admin.logs_placeholder': 'Marcador de posición de registros de actividad del sistema',
      'dashboard.admin.button_download_logs': 'Descargar Registros',
      'dashboard.admin.logs_help1': 'Los registros del sistema y los registros de actividad se mostrarán aquí.',
      'dashboard.admin.logs_help2': 'Esto incluirá actividades de usuarios, acciones administrativas y eventos del sistema.',

      // Dashboard Redirect Page
      'dashboard.redirect.loading_dashboard': 'Cargando Panel...',
      'dashboard.redirect.determining_role': 'Determinando tu rol y redirigiendo tu panel.',

      // Component Messages
      'component.header.logout': 'Cerrar Sesión',
      'component.header.welcome': 'Bienvenido,',
      'component.protected_route.verifying': 'Verificando autenticación...',
      'component.protected_route.access_denied': 'Acceso Denegado',
      'component.protected_route.signin_required': 'Necesitas iniciar sesión para acceder a esta página.',
      'component.protected_route.redirecting': 'Te estamos redirigiendo a iniciar sesión...',
      'component.role_gate.access_restricted': 'Acceso Restringido',
      'component.role_gate.no_permission': 'No tienes permiso para ver este contenido.',
      'component.role_gate.contact_support': 'Contacta al soporte si crees que esto es un error.',
      'component.role_gate.employer_feature_title': 'Característica del Empleador',
      'component.role_gate.employer_feature_desc': 'Esta característica está disponible solo para cuentas de empleadores.',
      'component.role_gate.admin_only_title': 'Solo Administrador',
      'component.role_gate.admin_only_desc': 'Esta característica está restringida a administradores.',
      'component.dashboard.loading_dashboard': 'Cargando Panel de Control...',
      'component.dashboard.determining_role': 'Determinando tu rol y redirigiendo a tu panel de control.',
      'component.dashboard.account_type': 'Tipo de Cuenta',

      // Auth Service Messages
      'auth.error_all_fields_required': 'Todos los campos son obligatorios: correo electrónico, contraseña, nombre, apellido, rol',
      'auth.error_invalid_role': 'Rol inválido. Debe ser uno de: job_seeker, employer, advertiser',
      'auth.error_unexpected_signup': 'Ocurrió un error inesperado durante el registro',
      'auth.error_email_password_required': 'Se requieren correo electrónico y contraseña',
      'auth.error_unexpected_login': 'Ocurrió un error inesperado durante el inicio de sesión',
      'auth.error_unexpected_logout': 'Ocurrió un error inesperado durante el cierre de sesión',
      'auth.error_unexpected_get_user': 'Ocurrió un error inesperado al obtener el usuario actual',
      'auth.error_user_id_required': 'Se requiere userId',
      'auth.error_user_not_found': 'Usuario no encontrado',
      'auth.error_unexpected_get_role': 'Ocurrió un error inesperado al obtener el rol del usuario',

      // Job Posting Service Messages
      'jobPosting.error_job_data_required': 'Se requieren datos del empleo',
      'jobPosting.error_user_id_required': 'Se requiere ID de usuario para publicar un empleo',
      'jobPosting.error_title_required': 'Se requiere el título del empleo y debe tener al menos 3 caracteres',
      'jobPosting.error_company_required': 'Se requiere el nombre de la empresa',
      'jobPosting.error_category_required': 'Se requiere la categoría del empleo',
      'jobPosting.error_city_required': 'Se requiere la ciudad',
      'jobPosting.error_state_required': 'Se requiere el estado',
      'jobPosting.error_state_invalid': 'El estado debe ser una abreviatura válida de estado estadounidense (p. ej., CA, NY, TX)',
      'jobPosting.error_description_required': 'Se requiere la descripción del empleo y debe tener al menos 20 caracteres',
      'jobPosting.error_email_required': 'Se requiere el correo electrónico de contacto',
      'jobPosting.error_email_invalid': 'El correo electrónico de contacto debe ser una dirección de correo válida',
      'jobPosting.error_mason_attestation_required': 'Se requiere la auto-certificación de Mason en Buen Estado para publicar',
      'jobPosting.error_compensation_format': 'El rango de compensación debe estar en formato: $50,000 - $75,000 o similar',
      'jobPosting.error_unexpected': 'Ocurrió un error inesperado al publicar el empleo',

      // Stripe Checkout Messages
      'stripe.error_missing_parameters': 'Faltan parámetros requeridos: productType, userId e itemId',
      'stripe.error_not_configured': 'Stripe aún no está configurado',
      'stripe.error_invalid_product_type': 'Tipo de producto inválido',
      'stripe.error_create_session_failed': 'Error al crear la sesión de pago',
      'stripe.error_no_session_id': 'No se devolvió ningún ID de sesión desde el servidor',
      'stripe.error_redirect_failed': 'Error al redirigir al pago',
      'stripe.error_unexpected': 'Ocurrió un error inesperado',

      // Admin Service Messages
      'admin.error_job_id_required': 'Se requiere el ID del empleo',
      'admin.error_order_id_required': 'Se requiere el ID del pedido',
      'admin.error_unexpected_pending_jobs': 'Ocurrió un error inesperado al obtener empleos pendientes',
      'admin.error_unexpected_pending_orders': 'Ocurrió un error inesperado al obtener órdenes de publicidad pendientes',
      'admin.error_unexpected_approve_job': 'Ocurrió un error inesperado al aprobar el empleo',
      'admin.error_unexpected_featured_status': 'Ocurrió un error inesperado al actualizar el estado destacado',
      'admin.error_unexpected_approve_order': 'Ocurrió un error inesperado al aprobar la orden de publicidad',

      // Post Job Page Messages
      'page.post_job.must_be_logged_in': 'Por favor, inicia sesión como empleador para publicar un empleo.',
      'page.post_job.login_prompt_description': 'Para publicar ofertas de trabajo y conectar con candidatos calificados en la comunidad masónica, debes crear una cuenta de empleador o iniciar sesión.',
      'page.post_job.sign_in_button': 'Iniciar Sesión',
      'page.post_job.create_account_button': 'Crear Cuenta de Empleador',
      'page.post_job.access_denied': 'Acceso Denegado',
      'page.post_job.employer_only': 'Esta página es solo para empleadores. Por favor, inicia sesión con una cuenta de empleador o crea una nueva cuenta de empleador.',
      'page.post_job.return_dashboard': 'Volver al Panel',
      'page.post_job.job_posted_success': 'Tu empleo ha sido enviado y está pendiente de revisión.',
      'page.post_job.missing_user_or_job_id': 'La información del usuario o el ID del empleo falta',
      'page.post_job.featured_badge': 'DESTACADO',
      'page.post_job.duration': '30 días',

      // Advertising Page Messages
      'page.advertising.must_be_logged_in': 'Debes iniciar sesión para comprar publicidad',
      'page.advertising.price': '$199',
      'page.advertising.processing_button': 'Procesando...',
      'page.advertising.featured_badge': 'DESTACADO',

      // Register Page Messages (Spanish)
      'page.register.pending_intake_success': '¡Tu solicitud de registro ha sido recibida!',

      // Button and Common Terms
      'common.yes': 'Sí',
      'common.no': 'No',
      'common.ok': 'OK',
      'common.cancel': 'Cancelar',
      'common.submit': 'Enviar',
      'common.back': 'Atrás',
      'common.next': 'Siguiente',
      'common.save': 'Guardar',
      'common.delete': 'Eliminar',
      'common.edit': 'Editar',
      'common.close': 'Cerrar',
      'common.loading': 'Cargando...',
      'common.error': 'Error',
      'common.success': 'Éxito',
      'common.warning': 'Advertencia',
      'common.info': 'Información',
    },
  }

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
