export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.15" }
  public: {
    Tables: {
      application_materials: { Row: { application_id: string | null; cover_letter_model: string | null; cover_letter_text: string; created_at: string; id: string; job_id: string; last_generated_at: string | null; notes: string; prompt_version: string | null; resume_model: string | null; tailored_resume_text: string; updated_at: string; user_id: string }; Insert: { application_id?: string | null; cover_letter_model?: string | null; cover_letter_text?: string; created_at?: string; id?: string; job_id: string; last_generated_at?: string | null; notes?: string; prompt_version?: string | null; resume_model?: string | null; tailored_resume_text?: string; updated_at?: string; user_id: string }; Update: Partial<{ application_id: string | null; cover_letter_model: string | null; cover_letter_text: string; created_at: string; id: string; job_id: string; last_generated_at: string | null; notes: string; prompt_version: string | null; resume_model: string | null; tailored_resume_text: string; updated_at: string; user_id: string }>; Relationships: [] }
      application_status_events: { Row: { application_id: string; created_at: string; from_status: Database["public"]["Enums"]["application_status"] | null; id: string; note: string | null; occurred_at: string; to_status: Database["public"]["Enums"]["application_status"] }; Insert: { application_id: string; created_at?: string; from_status?: Database["public"]["Enums"]["application_status"] | null; id?: string; note?: string | null; occurred_at?: string; to_status: Database["public"]["Enums"]["application_status"] }; Update: Partial<{ application_id: string; created_at: string; from_status: Database["public"]["Enums"]["application_status"] | null; id: string; note: string | null; occurred_at: string; to_status: Database["public"]["Enums"]["application_status"] }>; Relationships: [] }
      applications: { Row: { cover_letter_document_id: string | null; created_at: string; id: string; job_id: string; notes: string | null; resume_document_id: string | null; status: Database["public"]["Enums"]["application_status"]; submitted_at: string | null; updated_at: string; user_id: string }; Insert: { cover_letter_document_id?: string | null; created_at?: string; id?: string; job_id: string; notes?: string | null; resume_document_id?: string | null; status?: Database["public"]["Enums"]["application_status"]; submitted_at?: string | null; updated_at?: string; user_id: string }; Update: Partial<{ cover_letter_document_id: string | null; created_at: string; id: string; job_id: string; notes: string | null; resume_document_id: string | null; status: Database["public"]["Enums"]["application_status"]; submitted_at: string | null; updated_at: string; user_id: string }>; Relationships: [] }
      candidate_profiles: { Row: { created_at: string; email: string | null; full_name: string; github_url: string | null; headline: string | null; id: string; linkedin_url: string | null; location: string | null; phone: string | null; skills: string[]; updated_at: string; user_id: string; website_url: string | null; work_authorization: string | null; years_experience: number | null; address_line1: string | null; address_line2: string | null; city: string | null; region: string | null; postal_code: string | null; country: string | null; career_summary: string | null; experience_highlights: string | null; education: string | null; certifications: string | null; languages: string | null; is_mason: boolean; employer_discoverable: boolean }; Insert: { created_at?: string; email?: string | null; full_name?: string; github_url?: string | null; headline?: string | null; id?: string; linkedin_url?: string | null; location?: string | null; phone?: string | null; skills?: string[]; updated_at?: string; user_id: string; website_url?: string | null; work_authorization?: string | null; years_experience?: number | null; address_line1?: string | null; address_line2?: string | null; city?: string | null; region?: string | null; postal_code?: string | null; country?: string | null; career_summary?: string | null; experience_highlights?: string | null; education?: string | null; certifications?: string | null; languages?: string | null; is_mason?: boolean; employer_discoverable?: boolean }; Update: Partial<{ created_at: string; email: string | null; full_name: string; github_url: string | null; headline: string | null; id: string; linkedin_url: string | null; location: string | null; phone: string | null; skills: string[]; updated_at: string; user_id: string; website_url: string | null; work_authorization: string | null; years_experience: number | null; address_line1: string | null; address_line2: string | null; city: string | null; region: string | null; postal_code: string | null; country: string | null; career_summary: string | null; experience_highlights: string | null; education: string | null; certifications: string | null; languages: string | null; is_mason: boolean; employer_discoverable: boolean }>; Relationships: [] }
      documents: { Row: { created_at: string; id: string; is_default: boolean; kind: Database["public"]["Enums"]["document_kind"]; mime_type: string | null; name: string; size_bytes: number | null; storage_path: string | null; updated_at: string; user_id: string }; Insert: { created_at?: string; id?: string; is_default?: boolean; kind?: Database["public"]["Enums"]["document_kind"]; mime_type?: string | null; name: string; size_bytes?: number | null; storage_path?: string | null; updated_at?: string; user_id: string }; Update: Partial<{ created_at: string; id: string; is_default: boolean; kind: Database["public"]["Enums"]["document_kind"]; mime_type: string | null; name: string; size_bytes: number | null; storage_path: string | null; updated_at: string; user_id: string }>; Relationships: [] }
      employer_profiles: { Row: { user_id: string; company_name: string; recruiter_name: string | null; website_url: string | null; created_at: string; updated_at: string }; Insert: { user_id: string; company_name: string; recruiter_name?: string | null; website_url?: string | null; created_at?: string; updated_at?: string }; Update: Partial<{ user_id: string; company_name: string; recruiter_name: string | null; website_url: string | null; created_at: string; updated_at: string }>; Relationships: [] }
      employer_interest_requests: { Row: { id: string; employer_user_id: string; candidate_user_id: string; message: string; status: "pending" | "accepted" | "declined"; created_at: string; updated_at: string }; Insert: { id?: string; employer_user_id: string; candidate_user_id: string; message: string; status?: "pending" | "accepted" | "declined"; created_at?: string; updated_at?: string }; Update: Partial<{ id: string; employer_user_id: string; candidate_user_id: string; message: string; status: "pending" | "accepted" | "declined"; created_at: string; updated_at: string }>; Relationships: [] }
      job_analyses: { Row: { created_at: string; fit_score: number; gaps: string[]; id: string; job_id: string; keyword_matches: string[]; missing_keywords: string[]; model: string | null; positioning: string | null; prompt_version: string | null; strengths: string[]; summary: string | null; updated_at: string; user_id: string }; Insert: { created_at?: string; fit_score?: number; gaps?: string[]; id?: string; job_id: string; keyword_matches?: string[]; missing_keywords?: string[]; model?: string | null; positioning?: string | null; prompt_version?: string | null; strengths?: string[]; summary?: string | null; updated_at?: string; user_id: string }; Update: Partial<{ created_at: string; fit_score: number; gaps: string[]; id: string; job_id: string; keyword_matches: string[]; missing_keywords: string[]; model: string | null; positioning: string | null; prompt_version: string | null; strengths: string[]; summary: string | null; updated_at: string; user_id: string }>; Relationships: [] }
      jobs: { Row: { ats_name: string | null; company: string; created_at: string; created_by: string; currency: string | null; description: string | null; employment_type: Database["public"]["Enums"]["employment_type"] | null; id: string; location: string | null; posted_at: string | null; salary_max: number | null; salary_min: number | null; source_url: string | null; title: string; updated_at: string; work_arrangement: Database["public"]["Enums"]["work_arrangement"] | null }; Insert: { ats_name?: string | null; company: string; created_at?: string; created_by: string; currency?: string | null; description?: string | null; employment_type?: Database["public"]["Enums"]["employment_type"] | null; id?: string; location?: string | null; posted_at?: string | null; salary_max?: number | null; salary_min?: number | null; source_url?: string | null; title: string; updated_at?: string; work_arrangement?: Database["public"]["Enums"]["work_arrangement"] | null }; Update: Partial<{ ats_name: string | null; company: string; created_at: string; created_by: string; currency: string | null; description: string | null; employment_type: Database["public"]["Enums"]["employment_type"] | null; id: string; location: string | null; posted_at: string | null; salary_max: number | null; salary_min: number | null; source_url: string | null; title: string; updated_at: string; work_arrangement: Database["public"]["Enums"]["work_arrangement"] | null }>; Relationships: [] }
      saved_answers: { Row: { answer: string; created_at: string; id: string; question: string; tags: string[]; updated_at: string; user_id: string }; Insert: { answer?: string; created_at?: string; id?: string; question: string; tags?: string[]; updated_at?: string; user_id: string }; Update: Partial<{ answer: string; created_at: string; id: string; question: string; tags: string[]; updated_at: string; user_id: string }>; Relationships: [] }
      stripe_webhook_events: { Row: { event_id: string; event_type: string; processed_at: string }; Insert: { event_id: string; event_type: string; processed_at?: string }; Update: Partial<{ event_id: string; event_type: string; processed_at: string }>; Relationships: [] }
      submission_attempts: { Row: { application_id: string; ats_provider: Database["public"]["Enums"]["ats_provider"]; automation_provider: string | null; available_facts: Json; completed_at: string | null; created_at: string; dry_run: boolean; error_category: string | null; error_message: string | null; evidence: Json; id: string; idempotency_key: string | null; receipt_id: string | null; started_at: string | null; state: Database["public"]["Enums"]["submission_state"]; target_url: string | null; unresolved_questions: Json; updated_at: string; user_id: string }; Insert: { application_id: string; ats_provider?: Database["public"]["Enums"]["ats_provider"]; automation_provider?: string | null; available_facts?: Json; completed_at?: string | null; created_at?: string; dry_run?: boolean; error_category?: string | null; error_message?: string | null; evidence?: Json; id?: string; idempotency_key?: string | null; receipt_id?: string | null; started_at?: string | null; state?: Database["public"]["Enums"]["submission_state"]; target_url?: string | null; unresolved_questions?: Json; updated_at?: string; user_id: string }; Update: Partial<{ application_id: string; ats_provider: Database["public"]["Enums"]["ats_provider"]; automation_provider: string | null; available_facts: Json; completed_at: string | null; created_at: string; dry_run: boolean; error_category: string | null; error_message: string | null; evidence: Json; id: string; idempotency_key: string | null; receipt_id: string | null; started_at: string | null; state: Database["public"]["Enums"]["submission_state"]; target_url: string | null; unresolved_questions: Json; updated_at: string; user_id: string }>; Relationships: [] }
      submission_receipts: { Row: { answers: Json; application_id: string; application_url: string | null; ats_name: string | null; confirmation_text: string | null; cover_letter_document_id: string | null; created_at: string; id: string; resume_document_id: string | null; screenshot_path: string | null; submitted_at: string | null; updated_at: string; verified: boolean }; Insert: { answers?: Json; application_id: string; application_url?: string | null; ats_name?: string | null; confirmation_text?: string | null; cover_letter_document_id?: string | null; created_at?: string; id?: string; resume_document_id?: string | null; screenshot_path?: string | null; submitted_at?: string | null; updated_at?: string; verified?: boolean }; Update: Partial<{ answers: Json; application_id: string; application_url: string | null; ats_name: string | null; confirmation_text: string | null; cover_letter_document_id: string | null; created_at: string; id: string; resume_document_id: string | null; screenshot_path: string | null; submitted_at: string | null; updated_at: string; verified: boolean }>; Relationships: [] }
      subscriptions: { Row: { user_id: string; stripe_customer_id: string | null; stripe_subscription_id: string | null; plan: "basic" | "pro" | "auto" | null; status: "incomplete" | "trialing" | "active" | "past_due" | "canceled" | "unpaid" | "paused"; trial_ends_at: string | null; current_period_end: string | null; cancel_at_period_end: boolean; updated_at: string }; Insert: { user_id: string; stripe_customer_id?: string | null; stripe_subscription_id?: string | null; plan?: "basic" | "pro" | "auto" | null; status?: "incomplete" | "trialing" | "active" | "past_due" | "canceled" | "unpaid" | "paused"; trial_ends_at?: string | null; current_period_end?: string | null; cancel_at_period_end?: boolean; updated_at?: string }; Update: Partial<{ user_id: string; stripe_customer_id: string | null; stripe_subscription_id: string | null; plan: "basic" | "pro" | "auto" | null; status: "incomplete" | "trialing" | "active" | "past_due" | "canceled" | "unpaid" | "paused"; trial_ends_at: string | null; current_period_end: string | null; cancel_at_period_end: boolean; updated_at: string }>; Relationships: [] }
      user_preferences: { Row: { created_at: string; currency: string | null; desired_locations: string[]; desired_titles: string[]; email_notifications: boolean; id: string; min_salary: number | null; updated_at: string; user_id: string; weekly_digest: boolean; work_arrangements: Database["public"]["Enums"]["work_arrangement"][] }; Insert: { created_at?: string; currency?: string | null; desired_locations?: string[]; desired_titles?: string[]; email_notifications?: boolean; id?: string; min_salary?: number | null; updated_at?: string; user_id: string; weekly_digest?: boolean; work_arrangements?: Database["public"]["Enums"]["work_arrangement"][] }; Update: Partial<{ created_at: string; currency: string | null; desired_locations: string[]; desired_titles: string[]; email_notifications: boolean; id: string; min_salary: number | null; updated_at: string; user_id: string; weekly_digest: boolean; work_arrangements: Database["public"]["Enums"]["work_arrangement"][] }>; Relationships: [] }
    }
    Views: { [_ in never]: never }
    Functions: {
      search_discoverable_candidates: {
        Args: { masons_only?: boolean }
        Returns: Array<{ user_id: string; full_name: string; headline: string | null; city: string | null; region: string | null; country: string | null; career_summary: string | null; experience_highlights: string | null; education: string | null; certifications: string | null; languages: string | null; skills: string[]; is_mason: boolean }>
      }
    }
    Enums: {
      application_status: "draft" | "submitted" | "in_review" | "interview" | "offer" | "rejected" | "withdrawn"
      ats_provider: "greenhouse" | "lever" | "ashby" | "workday" | "unknown"
      document_kind: "resume" | "cover_letter" | "transcript" | "portfolio" | "other"
      employment_type: "full_time" | "part_time" | "contract" | "internship"
      submission_state: "draft" | "queued" | "running" | "needs_user_input" | "succeeded" | "failed" | "cancelled"
      work_arrangement: "onsite" | "hybrid" | "remote"
    }
    CompositeTypes: { [_ in never]: never }
  }
}
